<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:gba:sqg"
	targetNamespace="urn:gba:sqg" elementFormDefault="qualified" attributeFormDefault="unqualified">
<!--
=========================================================================================================
Dieses Schema ist Bestandteil der XML-Spezifikation für Datenübermittelung in der Externen Qualitätssicherung und wurde vom
Institut für Qualitätssicherung und Transparenz im Gesundheitswesen im Rahmen seiner Aufgaben als Institution nach § 137a SGB V erstellt.
Die Nutzungsbedingungen entnehmen Sie bitte dem Dokument unter:
https://iqtig.org/impressum/
=========================================================================================================
-->
	<!-- 
========================================================================================================= 
Schema für:
Datei-Art: 		QS-Daten (PID-Verfahren)
Schnittstelle: 	Die Schnittstelle zwischen der Vertrauensstelle und der Bundesauswertungsstelle (VST > BAS)
Datenfluss:	Follow-Up
=========================================================================================================
-->
	<xs:include schemaLocation="../abstract/sqg_root.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_header_content.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_software_le.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_document.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_encryption_feedbackkey_enc.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_body_content_le.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_cases_qs.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_case_da_pid.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_case_admin_default.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_patient_pseudonym.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_qs_data_enc.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_care_provider_enc.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_header_protocol.xsd"/>

	<xs:element name="root" type="sqg_root_type"/>
</xs:schema>
