@startuml profil-vererbung
!define MII_COLOR #FFF3E0
!define SENO_COLOR #E8F5E9

skinparam class {
  FontSize 11
}
skinparam linetype ortho
top to bottom direction

title Profilvererbung – Senologie-Profile

package "Diagnose" {
  class "MII_PR_Onko_Diagnose\nPrimaertumor\n//(Condition)//" as mii_diag MII_COLOR
  class "**Senologie_Diagnose\nMaligne**" as s_diag SENO_COLOR
  class "**Senologie_Diagnose\nBenigne**\n//erbt direkt von Condition//" as s_diag_b SENO_COLOR

  s_diag --|> mii_diag
}

package "Operative Therapie" {
  class "MII_PR_Onko_Mamma\nOperation\n//(Procedure)//" as mii_op MII_COLOR

  class "**Senologie_Operation**" as s_op SENO_COLOR
  class "**Senologie_OP_Planung**\n//erbt von ServiceRequest//" as s_plan SENO_COLOR
  class "**Senologie_Implantat**\n//erbt von Device//" as s_impl SENO_COLOR
  class "**Senologie_Operative\nKomplikation**\n//erbt von Observation//" as s_komp SENO_COLOR

  s_op --|> mii_op
}

package "Systemische Therapie" {
  class "MII_PR_Onko_Systemische\nTherapie\n//(Procedure)//" as mii_sys MII_COLOR
  class "MII_PR_Onko_Systemische\nTherapie_Medikation\n//(MedicationStatement)//" as mii_med MII_COLOR

  class "**Senologie_Systemtherapie\nProcedure**" as s_sysp SENO_COLOR
  class "**Senologie_Systemtherapie\nMedikation**" as s_sysm SENO_COLOR
  class "**Senologie_Geplante\nSystemtherapie**\n//erbt von MedicationRequest//" as s_sysg SENO_COLOR
  class "**Senologie_Begleit\nmedikation**\n//erbt von MedicationStatement//" as s_bmed SENO_COLOR

  s_sysp --|> mii_sys
  s_sysm --|> mii_med
}

package "Strahlentherapie" {
  class "MII_PR_Onko\nStrahlentherapie\n//(Procedure)//" as mii_rt MII_COLOR
  class "**Senologie\nStrahlentherapie**" as s_rt SENO_COLOR

  s_rt --|> mii_rt
}

package "Bildgebung" {
  class "MII_PR_Bildgebung\nKoerperstruktur\n//(BodyStructure)//" as mii_body MII_COLOR

  class "**Senologie_Bildgebung\nBefund**\n//erbt von DiagnosticReport//" as s_bild SENO_COLOR
  class "**Senologie_Bildgebung\nObservation**\n//erbt von Observation//" as s_bildo SENO_COLOR
  class "**Senologie_Bildgebung\nSonstige**\n//erbt von DiagnosticReport//" as s_bilds SENO_COLOR
  class "**Senologie\nTumorlokalisation**" as s_loc SENO_COLOR

  s_loc --|> mii_body
}

package "Pathologie" {
  class "MII_PR_Patho\nReport\n//(DiagnosticReport)//" as mii_patho MII_COLOR
  class "MII_PR_Patho\nSpecimen\n//(Specimen)//" as mii_spec MII_COLOR

  class "**Senologie_Pathologie\nBefund**" as s_patho SENO_COLOR
  class "**Senologie_Pathologie\nPraeparat**" as s_spec SENO_COLOR

  s_patho --|> mii_patho
  s_spec --|> mii_spec
}

package "Anamnese & Risiko" {
  class "**Senologie_Klinische\nUntersuchung**\n//erbt von Observation//" as s_klin SENO_COLOR
  class "**Senologie_Gynaekologische\nAnamnese**\n//erbt von Observation//" as s_gyn SENO_COLOR
  class "**Senologie\nFamilienanamnese**\n//erbt von FamilyMemberHistory//" as s_fam SENO_COLOR
  class "**Senologie\nGenexpressionstest**\n//erbt von RiskAssessment//" as s_gen SENO_COLOR
  class "**Senologie_Genexpressions\nScore**\n//erbt von Observation//" as s_score SENO_COLOR
}

package "Planung & Workflow" {
  class "**Senologie_Tumorboard\nEmpfehlung**\n//erbt von CarePlan//" as s_tb SENO_COLOR
  class "**Senologie\nStudienteilnahme**\n//erbt von ResearchSubject//" as s_study SENO_COLOR
}

legend right
  |= Farbe |= Ebene |
  | <back:FFF3E0> </back> | MII Kerndatensatz (Parent) |
  | <back:E8F5E9> </back> | Senologie-Profil |
  | //kursiv// | FHIR R4 Basisressource |
  Pfeile zeigen Vererbung (erbt von)
endlegend

@enduml
