<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <!--
=========================================================================================================
Dieses Schema ist Bestandteil der XML-Spezifikation für Datenübermittelung in der Externen Qualitätssicherung und wurde vom 
Institut für Qualitätssicherung und Transparenz im Gesundheitswesen im Rahmen seiner Aufgaben als Institution nach § 137a SGB V erstellt.
Die Nutzungsbedingungen entnehmen Sie bitte dem Dokument unter:
https://iqtig.org/impressum/
=========================================================================================================
-->
  <xs:include schemaLocation="../../sqg_datatypes.xsd"/>
  <xs:include schemaLocation="../../abstract/sqg_qs_data_base.xsd"/>
  <xs:complexType name="qs_data_papsy_type">
    <xs:complexContent>
      <xs:extension base="qs_data_type">
        <xs:sequence>
          <xs:element name="B" type="gr_bpapsy_type">
            <xs:annotation>
              <xs:documentation>Bogen: Basis // Bogenzahl: 1 </xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="module" use="required">
          <xs:simpleType>
            <xs:restriction base="enum_exportmodul_type">
              <xs:enumeration value="PAPSY_KV"/>
              <xs:enumeration value="PAPSY_SV"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="tds_bpapsy_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:annotation>
          <xs:documentation>Exportfelder des Bogens</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="DokAbschlDat">
              <xs:annotation>
                <xs:documentation>ZusatzFeld: Dokumentationsabschlussdatum</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="datum_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="STATUSLEAPSY">
              <xs:annotation>
                <xs:documentation>BogenFeld: Status der Leistungserbringung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_statuslept_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="kasseiknr2Stellen">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Ersatzfeld Institutionskennzeichen der Krankenkasse der Versichertenkarte</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="[0-9]{2}"/>
                      <xs:maxLength value="2"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="versichertenstatusgkvamb">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: GKV-Versichertenstatus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:totalDigits value="1"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="GRUPPENTH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Hat die Patientin/ der Patient im Rahmen der gesamten Behandlung an einer ambulanten Gruppentherapie teilgenommen?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KJPSYT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Behandlung als Kinder- und Jugendlichenpsychotherapie</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ThBegvorRL">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Therapiebeginn vor dem 1. September 2024</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="DauerTh">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Dauer der Therapie in Tagen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:totalDigits value="4"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENDRLTP">
              <xs:annotation>
                <xs:documentation>BogenFeld: Enddatum dieser Richtlinientherapie</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="datum_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="gebjahr">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Geburtsjahr</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:gYear" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AlterzuBeg">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Der Patient war zu Beginn der Therapie mindestens 18 Jahre alt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="3" minOccurs="1" name="EBM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Welches psychotherapeutische Verfahren wurde angewendet? (GOP für die psychotherapeutische Sitzung und Pseudo-GOP für Therapieende);
ausgelöste EBM-Ziffer(n)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="ebm_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="10" minOccurs="1" name="ENTLDIAG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Diagnose(n)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="icd10_type" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="gr_bpapsy_type">
    <xs:complexContent>
      <xs:extension base="tds_bpapsy_type">
        <xs:sequence>
          <xs:element name="bogen">
            <xs:annotation>
              <xs:documentation>Kindbögen</xs:documentation>
            </xs:annotation>
            <xs:complexType>
              <xs:sequence>
                <xs:element minOccurs="0" name="ET" type="tds_etpapsy_type">
                  <xs:annotation>
                    <xs:documentation>Bogen: Einzeltherapie</xs:documentation>
                  </xs:annotation>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="tds_etpapsy_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:annotation>
          <xs:documentation>Exportfelder des Bogens</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="LFDNRTDS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wievielter optionaler Teildatensatz?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="1"/>
                      <xs:totalDigits value="2"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="ORTLEAPSY">
              <xs:annotation>
                <xs:documentation>BogenFeld: Ort der Leistungserbringung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_ortleapsy_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GESCHLECHTDEK">
              <xs:annotation>
                <xs:documentation>BogenFeld: Geschlecht</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_geschlechtdek_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GRUBEE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Grund der Beendigung dieser Richtlinientherapie</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_grundbeend_type" use="required"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
