<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <!--
=========================================================================================================
Dieses Schema ist Bestandteil der XML-Spezifikation für Datenübermittelung in der Externen Qualitätssicherung und wurde vom 
Institut für Qualitätssicherung und Transparenz im Gesundheitswesen im Rahmen seiner Aufgaben als Institution nach § 137a SGB V erstellt.
Die Nutzungsbedingungen entnehmen Sie bitte dem Dokument unter:
https://iqtig.org/impressum/
=========================================================================================================
-->
  <xs:include schemaLocation="../../sqg_datatypes.xsd"/>
  <xs:include schemaLocation="../../abstract/sqg_qs_data_base.xsd"/>
  <xs:complexType name="qs_data_htxm_type">
    <xs:complexContent>
      <xs:extension base="qs_data_type">
        <xs:sequence>
          <xs:element name="B" type="gr_bhtxm_type">
            <xs:annotation>
              <xs:documentation>Bogen: Basis // Bogenzahl: 1 </xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
        <xs:attribute fixed="HTXM" name="module" type="enum_exportmodul_type" use="required">
          <xs:annotation>
            <xs:documentation>Herztransplantation, Herzunterstützungssysteme/Kunstherzen</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="tds_bhtxm_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:annotation>
          <xs:documentation>Exportfelder des Bogens</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="DokAbschlDat">
              <xs:annotation>
                <xs:documentation>ZusatzFeld: Dokumentationsabschlussdatum</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="datum_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="kasseiknr2Stellen">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Ersatzfeld Institutionskennzeichen der Krankenkasse der Versichertenkarte</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="[0-9]{2}"/>
                      <xs:maxLength value="2"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="versichertenstatusgkv">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: GKV-Versichertenstatus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:totalDigits value="1"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="VERSICHERTENIDNEUNV">
              <xs:annotation>
                <xs:documentation>BogenFeld: Der Patient verfügt über keine eGK-Versichertennummer</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="BSNR">
              <xs:annotation>
                <xs:documentation>BogenFeld: Betriebsstätten-Nummer</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="[0-9]{1,2}"/>
                      <xs:maxLength value="2"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Aufnahmedatum Krankenhaus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="datum_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="alter">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Patientenalter am Aufnahmetag in Jahren</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:totalDigits value="7"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="monatAufn">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Monat des Aufnahmetages</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="mondatum_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="FACHABT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Fachabteilung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="fachabt_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="gebjahr">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Geburtsjahr</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:gYear" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GESCHLECHT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Geschlecht</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_geschlecht_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GRUNDERKRANK">
              <xs:annotation>
                <xs:documentation>BogenFeld: Grunderkrankung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_grunderkrankunghtx_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="DIABETESHTX">
              <xs:annotation>
                <xs:documentation>BogenFeld: Diabetes mellitus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_diabeteshtx_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="VOROPTHORAKALJN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wurden vor der stationären Aufnahme thorakale Operationen (offen-chirurgisch) am Patienten durchgeführt?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="VOROPHTX">
              <xs:annotation>
                <xs:documentation>BogenFeld: Herztransplantation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="VOROPTAH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Assist Device/TAH</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="VOROPKCH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Koronarchirurgie</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="VOROPAOKL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Klappenchirurgie</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="VOROPVITIUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Korrektur angeborener Vitien</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="VOROPSONST">
              <xs:annotation>
                <xs:documentation>BogenFeld: sonstige</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ANZVOROP">
              <xs:annotation>
                <xs:documentation>BogenFeld: Anzahl aller offen-chirurgischen Voroperationen am Herzen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="0"/>
                      <xs:totalDigits value="2"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="ANZVOROPUNB">
              <xs:annotation>
                <xs:documentation>BogenFeld: Anzahl aller offen-chirurgischen Voroperationen unbekannt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="VOROPDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Datum der letzten thorakalen (offen-chirurgisch) Voroperation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="datum_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="abstVorop">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Abstand zwischen Aufnahmedatum und Voroperation in Tagen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:totalDigits value="7"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="abstVoropGebdatum">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Abstand zwischen Geburtsdatum und letzter thorakaler Voroperation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:totalDigits value="7"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="HTXJN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wurde während des stationären Aufenthaltes eine isolierte Herztransplantation durchgeführt?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="HEPATITISB">
              <xs:annotation>
                <xs:documentation>BogenFeld: Hepatitis B</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="HEPATITISC">
              <xs:annotation>
                <xs:documentation>BogenFeld: Hepatitis C</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="BLUTGRUPPE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Blutgruppe</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_blutgruppe_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="RHESUSFAKTOR">
              <xs:annotation>
                <xs:documentation>BogenFeld: Rhesusfaktor</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_rhesus_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="VADTAHJN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wurde während des stationären Aufenthaltes ein Herzunterstützungssystem / Kunstherz implantiert?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="WARTELISTE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Befand sich der Patient vor oder während des stationären Aufenthaltes auf der Warteliste für eine Herztransplantation?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="EINWBAS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Liegt eine wirksame Einwilligung des Patienten zur weiteren Verarbeitung personenbezogener QS-Daten (einschließlich ET-Nummer) in der Bundesauswertungsstelle vor?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="EINWTXREG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Liegt eine wirksame Einwilligung des Patienten zur weiteren Übermittlung personenbezogener QS-Daten (einschließlich ET-Nummer) an das Transplantationsregister vor?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="EINWTXREGAUFK">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wurde der Patient im Rahmen eines ärztlichen Aufklärungsgesprächs über die Einwilligung und die Folgen eines möglichen Widerrufs der Einwilligung zur Übermittlung der personenbezogenen Daten an das Transplantationsregister aufgeklärt?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jnu_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsdatum Krankenhaus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="datum_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="entlwochtag">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Wochentag 1 - 7</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_wochentag_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="vwDauer">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Verweildauer im Krankenhaus in Tagen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="0"/>
                      <xs:totalDigits value="7"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="monatEntl">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Monat des Entlassungstages</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="mondatum_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="30" name="ENTLDIAG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsdiagnose(n);
alle Entlassungsdiagnosen, die in inhaltlichem Zusammenhang mit der in diesem Leistungsbereich dokumentierten Leistung stehen &#13;
&#13;
ICD-10-GM</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="icd10_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLGRUND">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsgrund</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_entlgrund_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="NICHTSPEZENTLGRUND">
              <xs:annotation>
                <xs:documentation>BogenFeld: nicht spezifizierter Entlassungsgrund</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="TODESURSACHEMP">
              <xs:annotation>
                <xs:documentation>BogenFeld: Todesursache(n) akut</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_todesursacheakut_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLVADTAH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wurde der Patient mit einem Herzunterstützungssystem / Kunstherzen entlassen, das während des stationären Aufenthaltes implantiert wurde?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="gr_bhtxm_type">
    <xs:complexContent>
      <xs:extension base="tds_bhtxm_type">
        <xs:sequence>
          <xs:element name="bogen">
            <xs:annotation>
              <xs:documentation>Kindbögen</xs:documentation>
            </xs:annotation>
            <xs:complexType>
              <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="M" type="tds_mhtxm_type">
                  <xs:annotation>
                    <xs:documentation>Bogen: Implantation Herzunterstützungssystem/Kunstherz // Existenzbedingung: VADTAHJN = 1 // Bogenzahl: * </xs:documentation>
                  </xs:annotation>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="T" type="tds_thtxm_type">
                  <xs:annotation>
                    <xs:documentation>Bogen: Transplantation // Existenzbedingung: HTXJN = 1 // Bogenzahl: * </xs:documentation>
                  </xs:annotation>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="tds_mhtxm_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:annotation>
          <xs:documentation>Exportfelder des Bogens</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="LFDNRVADTAH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wievielte Implantation während dieses Aufenthaltes?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="1"/>
                      <xs:totalDigits value="2"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="EINGRIFFMKU">
              <xs:annotation>
                <xs:documentation>BogenFeld: durchgeführter Eingriff</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_durchgefuehrtereingriff_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ZIELSTELLUNG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Zielstellung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_zielstellung_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="HERZINSUFFOP">
              <xs:annotation>
                <xs:documentation>BogenFeld: Lag bei dem Patienten zum Zeitpunkt des Eingriffs eine akute Herzinsuffizienz vor?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GEPLEINSATZDAUER">
              <xs:annotation>
                <xs:documentation>BogenFeld: geplante Einsatzdauer des Herzunterstützungssystems &gt; 7 Tage</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ASA">
              <xs:annotation>
                <xs:documentation>BogenFeld: Einstufung nach ASA-Klassifikation;
Es ist die ASA-Einstufung der Anästhesiedokumentation zu übernehmen.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_asa_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="INTERMACS">
              <xs:annotation>
                <xs:documentation>BogenFeld: INTERMACS Profile-Level 1 - 7</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_intermacslevel_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="LVEJEKFRAKTION35">
              <xs:annotation>
                <xs:documentation>BogenFeld: linksventrikuläre Ejektionsfraktion &gt; 35%</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jnnbb_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GEHTEST">
              <xs:annotation>
                <xs:documentation>BogenFeld: 6 Minuten Gehtest: Distanz &gt;= 500 Meter</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jnndnb_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="MAXO2AUFNAHME">
              <xs:annotation>
                <xs:documentation>BogenFeld: maximale Sauerstoffaufnahme &gt; 20 ml O2/min/kg Körpergewicht</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jnndnb_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="STATAUFNAHME12M">
              <xs:annotation>
                <xs:documentation>BogenFeld: dokumentierte stationäre Aufnahme aufgrund Linksherzdekompensation in den letzten 12 Monaten</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jnu_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="HERZINSUFFMEDIK">
              <xs:annotation>
                <xs:documentation>BogenFeld: Herzinsuffizienzmedikation bei dokumentiertem stationären Aufenthalt bekannt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="OPDATUMVADTAH">
              <xs:annotation>
                <xs:documentation>BogenFeld: OP-Datum</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="datum_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="poopvwdauerVADTAH">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Postoperative Verweildauer: Differenz in Tagen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:totalDigits value="7"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="monatOpVADTAH">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Monat der Operation (VAD/TAH)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="mondatum_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="10" name="OPSCHLUESSELVADTAH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Operation;
alle OPS-Kodes des durchgeführten Eingriffs</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="ops301_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="PUMPSYSTEM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Typ des Pumpsystems</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_pumpsystem_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="LAGEVADTAH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Lage des Herzunterstützungssystems / Kunstherzens</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_lagevadtah_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ARTSYSTEM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Art des Unterstützungssystems</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_unterstuetzungssystem_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ABBRUCHVADTAH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Abbruch der Implantation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="SEPSIS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Sepsis;
bei oder nach Implantation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="NEURODYSFUNKTION">
              <xs:annotation>
                <xs:documentation>BogenFeld: neurologische Dysfunktion</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="FEHLFNKTVADTAH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Fehlfunktion des Herzunterstützungssystems</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_fehlfnktvadtah_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="RECHTSHERZVERSAG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Rechtsherzversagen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tds_thtxm_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:annotation>
          <xs:documentation>Exportfelder des Bogens</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="LFDNREINGRIFF">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wievielte Transplantation während dieses Aufenthaltes?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="1"/>
                      <xs:totalDigits value="2"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="PRA">
              <xs:annotation>
                <xs:documentation>BogenFeld: PRA;
Panel Reactive Antibodies</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="0"/>
                      <xs:maxInclusive value="100"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="DRINGLICHKEITHTX">
              <xs:annotation>
                <xs:documentation>BogenFeld: Dringlichkeit</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_dringlichhtx_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="CASCORE">
              <xs:annotation>
                <xs:documentation>BogenFeld: CAS (Cardiac Allocation Score)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                      <xs:minInclusive value="0.0"/>
                      <xs:maxInclusive value="100.0"/>
                      <xs:totalDigits value="5"/>
                      <xs:fractionDigits value="2"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="LUNGEFWIDSTWERT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Lungengefäßwiderstand Wert</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="0"/>
                      <xs:totalDigits value="4"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNBEFUNDBEATMUNG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Beatmung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KREATININWERTMGDL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Kreatininwert i.S. in mg/dl;
präoperativ</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                      <xs:minInclusive value="0.0"/>
                      <xs:maxInclusive value="99.9"/>
                      <xs:totalDigits value="3"/>
                      <xs:fractionDigits value="1"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="KREATININWERTMOLL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Kreatininwert i.S. in µmol/l;
präoperativ</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="0"/>
                      <xs:totalDigits value="4"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="INDUKTHERAPIE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Induktionstherapie</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_induktherapie_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="INICYCLOSPORIN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Cyclosporin</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="INITACROLIMUS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Tacrolimus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="INIAZATHIOPRIN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Azathioprin</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="INIMYCOPHENOLAT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Mycophenolat</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="INICORTISON">
              <xs:annotation>
                <xs:documentation>BogenFeld: Steroide</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="INITORINHIBOTOR">
              <xs:annotation>
                <xs:documentation>BogenFeld: m-ToR-Inhibitor</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="INIIMMUNSUPPAND">
              <xs:annotation>
                <xs:documentation>BogenFeld: andere</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ALTERSPENHTX">
              <xs:annotation>
                <xs:documentation>BogenFeld: Spenderalter;
Alter in Jahren</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="0"/>
                      <xs:maxInclusive value="79"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="GESCHLECHTSPEN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Geschlecht</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_geschlecht_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KGROESSESPEN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Körpergröße</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="0"/>
                      <xs:totalDigits value="3"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="KGEWICHTSPEN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Körpergewicht</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="0"/>
                      <xs:totalDigits value="3"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="BLUTGRUPPESPEN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Blutgruppe</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_blutgruppe_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="RHESUSFAKTORSPEN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Rhesusfaktor</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_rhesus_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="TODESURSACHESPEN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Todesursache;
Spender</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_todesursachespen_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KATECHOLAMIN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Vasopressortherapie</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="CKWERT">
              <xs:annotation>
                <xs:documentation>BogenFeld: CK-Wert</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="0"/>
                      <xs:totalDigits value="5"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="CKMBWERT">
              <xs:annotation>
                <xs:documentation>BogenFeld: CK-MB-Wert</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="0"/>
                      <xs:totalDigits value="4"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="HERZSTILLSTAND">
              <xs:annotation>
                <xs:documentation>BogenFeld: Herzstillstand</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="HYPOTENSPERIOD">
              <xs:annotation>
                <xs:documentation>BogenFeld: hypotensive Periode</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KORONARANGIO">
              <xs:annotation>
                <xs:documentation>BogenFeld: Koronarangiographie erfolgt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ORGANQUALITAETENTN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Organqualität zum Zeitpunkt der Entnahme</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_organqualitaet_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="OCSYSTEM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Einsatz eines Perfusionssystems</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_einsatzperfusionsys_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KATEGORIESPENDERORGAN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Kategorie des Spenderorgans</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_katspenderorgan_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="HFADATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Datum des Eintritts des irreversiblen Hirnfunktionsausfalls</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="datum_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ORGENTDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Datum der Organentnahme</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="datum_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="HAEMATOKRITWERT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Hämatokrit (Hk)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="0"/>
                      <xs:maxInclusive value="100"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="OPDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: OP-Datum</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="datum_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="poopvwdauer">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Postoperative Verweildauer: Differenz in Tagen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:totalDigits value="7"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="monatOp">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Monat der Operation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="mondatum_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="10" name="OPSCHLUESSEL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Operation;
alle OPS-Kodes des durchgeführten Eingriffs</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="ops301_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ABBRUCHTX">
              <xs:annotation>
                <xs:documentation>BogenFeld: Abbruch der Transplantation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ORGANQUALITAETTRANS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Organqualität zum Zeitpunkt der Transplantation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_organqualitaet_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ISCHAEMIEZEITKALT">
              <xs:annotation>
                <xs:documentation>BogenFeld: kalte Ischämiezeit;
Die Dokumentation eines Wertes oberhalb von 720 ist nur bei Einsatz eines hypothermen (auch in Kombination mit normothermen) Perfusionssystems zulässig.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="1"/>
                      <xs:maxInclusive value="14400"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLCYCLOSPORIN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Cyclosporin</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLTACROLIMUS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Tacrolimus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLAZATHIOPRIN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Azathioprin</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLMYCOPHENOLAT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Mycophenolat</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLCORTISON">
              <xs:annotation>
                <xs:documentation>BogenFeld: Steroide</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLTORINHIBITOR">
              <xs:annotation>
                <xs:documentation>BogenFeld: m-ToR-Inhibitor</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLIMMUNSUPPAND">
              <xs:annotation>
                <xs:documentation>BogenFeld: andere</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ANZABSTOSSREAK">
              <xs:annotation>
                <xs:documentation>BogenFeld: Anzahl der behandelten Abstoßungsreaktionen;
0 = keine</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="0"/>
                      <xs:totalDigits value="2"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="ANZABSTOSSREAKUNB">
              <xs:annotation>
                <xs:documentation>BogenFeld: Anzahl der behandelten Abstoßungsreaktionen unbekannt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
