#!/usr/bin/env python3
"""
Erzeugt FHIR Library-Ressourcen aus den CQL-Dateien in input/cql/.

Output: input/fsh/measures/lib-*.fsh (eine FSH-Instance pro CQL-Datei)

Die Library-Resource enthält:
- name + version + url
- content[0].contentType = "text/cql"
- content[0].data = base64-encoded CQL-Code

Diese Library wird von Measure-Ressourcen referenziert und vom Server
für $evaluate-measure geladen.
"""
import base64
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CQL_DIR = REPO / "input/cql"
OUT_DIR = REPO / "input/fsh/measures"
BASE_URL = "https://www.senologie.org/fhir"

CQL_FILES = [
    ("MinimalMeasureLib.cql", "MinimalMeasureLib",
     "Minimale Debug-Library mit drei konstanten true-Defines"),
    ("QualitaetsindikatorenLeitlinie.cql", "QualitaetsindikatorenLeitlinie",
     "S3-Leitlinien-Qualitätsindikatoren (17 QIs aus S3 Mammakarzinom v5.0, Kapitel 8)"),
    ("OncoBoxBrustKennzahlen.cql", "OncoBoxBrustKennzahlen",
     "OncoBox Brust 2.0 Kennzahlen (KB-1 bis KB-20, DKG-Zertifizierung)"),
]


def build_library(cql_filename: str, library_name: str, description: str) -> str:
    cql_path = CQL_DIR / cql_filename
    cql_text = cql_path.read_text()
    # Extract version from library statement
    m = re.search(r"library\s+\S+\s+version\s+'([^']+)'", cql_text)
    version = m.group(1) if m else "0.1.0"
    b64 = base64.b64encode(cql_text.encode("utf-8")).decode("ascii")

    instance_id = library_name
    fsh = f'''// Auto-generated FHIR Library wrapper for {cql_filename}
// Generated by scripts/cql/build-libraries.py — do not edit by hand.

Instance: {instance_id}
InstanceOf: Library
Title: "Library: {library_name}"
Description: "{description}"
Usage: #definition

* url = "{BASE_URL}/Library/{instance_id}"
* name = "{library_name}"
* version = "{version}"
* status = #active
* experimental = false
* type = http://terminology.hl7.org/CodeSystem/library-type#logic-library
* content[+].contentType = #text/cql
* content[=].data = "{b64}"
'''
    return fsh


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for cql, name, desc in CQL_FILES:
        fsh = build_library(cql, name, desc)
        out_file = OUT_DIR / f"lib-{name.lower().replace('_','-')}.fsh"
        out_file.write_text(fsh)
        print(f"  → {out_file.relative_to(REPO)}")


if __name__ == "__main__":
    main()
