<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <!--
=========================================================================================================
Dieses Schema ist Bestandteil der XML-Spezifikation für Datenübermittelung in der Externen Qualitätssicherung und wurde vom 
Institut für Qualitätssicherung und Transparenz im Gesundheitswesen im Rahmen seiner Aufgaben als Institution nach § 137a SGB V erstellt.
Die Nutzungsbedingungen entnehmen Sie bitte dem Dokument unter:
https://iqtig.org/impressum/
=========================================================================================================
-->
  <xs:include schemaLocation="../../sqg_datatypes.xsd"/>
  <xs:include schemaLocation="../../abstract/sqg_qs_data_base.xsd"/>
  <xs:complexType name="qs_data_15n1_type">
    <xs:complexContent>
      <xs:extension base="qs_data_type">
        <xs:sequence>
          <xs:element name="B" type="gr_b15n1_type">
            <xs:annotation>
              <xs:documentation>Bogen: Basis // Bogenzahl: 1 </xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
        <xs:attribute fixed="15/1" name="module" type="enum_exportmodul_type" use="required">
          <xs:annotation>
            <xs:documentation>Gynäkologische Operationen</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="tds_b15n1_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:annotation>
          <xs:documentation>Exportfelder des Bogens</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="DokAbschlDat">
              <xs:annotation>
                <xs:documentation>ZusatzFeld: Dokumentationsabschlussdatum</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="datum_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="BSNR">
              <xs:annotation>
                <xs:documentation>BogenFeld: Betriebsstätten-Nummer</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="[0-9]{1,2}"/>
                      <xs:maxLength value="2"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="FACHABT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Fachabteilung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="fachabt_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="gebjahr">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Geburtsjahr</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:gYear" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Aufnahmedatum Krankenhaus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="datum_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="aufnquartal">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Quartal des Aufnahmetages</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="quartdatum_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="alter">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Patientenalter am Aufnahmetag in Jahren</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:totalDigits value="7"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="30" name="AUFNDIAG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Aufnahmediagnose(n);
ICD-10-GM</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="icd10_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsdatum Krankenhaus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="datum_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="vwDauer">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Verweildauer im Krankenhaus in Tagen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="0"/>
                      <xs:totalDigits value="7"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="entlquartal">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Quartal des Entlassungstages</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="quartdatum_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="entlwochtag">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Wochentag 1 - 7</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_wochentag_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="30" name="ENTLDIAG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsdiagnose(n);
alle Entlassungsdiagnosen, die in inhaltlichem Zusammenhang mit der in diesem Leistungsbereich dokumentierten Leistung stehen &#13;
&#13;
ICD-10-GM</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="icd10_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLGRUND">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsgrund</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_entlgrund_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="NICHTSPEZENTLGRUND">
              <xs:annotation>
                <xs:documentation>BogenFeld: nicht spezifizierter Entlassungsgrund</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="gr_b15n1_type">
    <xs:complexContent>
      <xs:extension base="tds_b15n1_type">
        <xs:sequence>
          <xs:element name="bogen">
            <xs:annotation>
              <xs:documentation>Kindbögen</xs:documentation>
            </xs:annotation>
            <xs:complexType>
              <xs:sequence>
                <xs:element maxOccurs="unbounded" name="O" type="tds_o15n1_type">
                  <xs:annotation>
                    <xs:documentation>Bogen: Operation // Existenzbedingung: keine // Bogenzahl: + </xs:documentation>
                  </xs:annotation>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="tds_o15n1_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:annotation>
          <xs:documentation>Exportfelder des Bogens</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="LFDNREINGRIFF">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wievielter gynäkologischer Eingriff während dieses Aufenthaltes?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="1"/>
                      <xs:totalDigits value="2"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="ASA">
              <xs:annotation>
                <xs:documentation>BogenFeld: Einstufung nach ASA-Klassifikation;
ASA</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_asa_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="VOROPGLEICH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Voroperation im OP-Gebiet</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="OPDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: OP-Datum</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="datum_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="poopvwdauer">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Postoperative Verweildauer: Differenz in Tagen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:totalDigits value="7"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="opquartal">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Quartal der Operation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="quartdatum_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="10" name="OPSCHLUESSEL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Operation;
alle OPS-Kodes des durchgeführten Eingriffs</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="ops301_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KONTRALATOVAR">
              <xs:annotation>
                <xs:documentation>BogenFeld: Ist das kontralaterale Ovar postoperativ noch vorhanden?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="IOPKOMPJN">
              <xs:annotation>
                <xs:documentation>BogenFeld: intraoperative Komplikationen;
durch diesen Eingriff</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="IOPKOMPLBLASE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Blase</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="IOPKOMPLHARNL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Harnleiter</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="IOPKOMPLURETHRA">
              <xs:annotation>
                <xs:documentation>BogenFeld: Urethra</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="IOPKOMPLDARM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Darm</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="IOPKOMPLUTERUS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Uterus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="IOPKOMPLGEFNERV">
              <xs:annotation>
                <xs:documentation>BogenFeld: Gefäß-/Nervenläsion</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="IOPKOMPLLAGER">
              <xs:annotation>
                <xs:documentation>BogenFeld: Lagerungsschaden</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="IOPKOMPLORGAN">
              <xs:annotation>
                <xs:documentation>BogenFeld: andere Organverletzungen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="IOPKOMPLANDERE">
              <xs:annotation>
                <xs:documentation>BogenFeld: andere intraoperative Komplikationen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="HISTOLJN">
              <xs:annotation>
                <xs:documentation>BogenFeld: postoperative Histologie</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="HISTOL">
              <xs:annotation>
                <xs:documentation>BogenFeld: führender Befund</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_histolopgyn_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ASSBLASSENTL">
              <xs:annotation>
                <xs:documentation>BogenFeld: assistierte Blasenentleerung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jn_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="WIEEINMALKATH">
              <xs:annotation>
                <xs:documentation>BogenFeld: wiederholte Einmalkatheterisierung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="TRANSDAUERKATH">
              <xs:annotation>
                <xs:documentation>BogenFeld: transurethraler Dauerkatheter</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="SUPRAPUBDAUERKATH">
              <xs:annotation>
                <xs:documentation>BogenFeld: suprapubischer Dauerkatheter</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_jleer_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ASSBLASSENTLDAUER">
              <xs:annotation>
                <xs:documentation>BogenFeld: Dauer der assistierten Blasenentleerung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_assblassentl_type" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
