Logical: BIH_LM_MolGen_Senologie
Parent: Element
Id: LogicalModelSenologie
Title: "BIH LM MolGen LogicalModel"
Description: "LogicalModel des BIH-Spezifkation des Moduls Senologie"
* insert PR_CS_VS_Version
* ^status = #draft

* Diagnose 0..1 BackboneElement "Diagnose Mamma"
  * Diagnosekode 0..1  CodeableConcept "Diagnose" "Diagnosestellung nach SNOMED CT"
  * DiagnoseB3SubTyp 0..* CodeableConcept "B3 Subtyp" "Abgebildet im KDS Modul Biobank"
  * Grad 0..1 CodeableConcept "Grad" "Grad der Mammaerkrankung"
  * Seite 0..1 CodeableConcept "Seite" "Seite der Mammaerkrankung"
  * DatumErstdiagnose 0..1 date "Datum der Erstdiagnose" "Datum der Erstdiagnose der Mammaerkrankung"
  * Diagnosesicherung 0..1 CodeableConcept "Diagnosesicherung" "Diagnosesicherung der Mammaerkrankung"
  * Metastasierungsstadium 0..1 CodeableConcept "Metastasierungsstadium" "Metastasierungsstadium der Mammaerkrankung"  
* Vorstellung 0..1 BackboneElement "Vorstellungsgrund"
  * Typ 0..1 CodeableConcept "Art der Vorstellung" "Erst- oder Verlaufsvorstellung"
  * Erstvorstellung 0..1 date "Datum der Erstvorstellung" "Datum der Erstvorstellung"
* AllgemeineAnamnese 0..1 BackboneElement "Allgemeine Anamnese"
  * EQ5D5L 0..* CodeableConcept "EQ5D5L" "Gesundheitszustand nach EQ5D5L"
* GynaekologischeAnamnese 0..1 BackboneElement "Gynäkologische Anamnese"
  * Menarche 0..1 date "Alter bei Menarche" "Alter bei Menarche"
* Familienanamnese 0..1 BackboneElement "Familienanamnese"
  * Alter 0..* CodeableConcept "Alter" "aktuelles Alter der Angehörigen"
* Medikation 0..* BackboneElement "Medikation"
  * Medikationsname 1..1 CodeableConcept "Name" "Name des Medikaments"
    * Dosis 0..1 CodeableConcept "Dosis" "Dosis des Medikaments"
    * Einheit 0..1 date "Einheit" "Einheit/ Darreichungsform der Medikation"
    * Dosierschema 0..1 string "Dosierschema" "Dosierschema"
* Studien 0..* BackboneElement "Studien"
  * Studienname 1..1 CodeableConcept "Name" "Name der Studie"
  * Screeningstatus 0..1 string "Screeningstatus" "Screeningstatus"
  * Studienarm 0..1 CodeableConcept "Studienarm" "Studienarm"
  * Aufklaerungsdatum 0..1 date "Aufklärungsdatum" "Datum der Aufklärung"
  * Teilnahmestatus 0..1 CodeableConcept "Teilnahmestatus" "Teilnahmestatus an der Studie"
  * Kontakt 0..1 ContactPoint "Kontakt" "Kontakt zur Studie"
* KlinischeUntersuchung 0..* BackboneElement "Klinische Untersuchung"
  * MammaRechts 0..1 BackboneElement "Untersuchung Mamma rechts"
    * MammaCABefund 0..1 CodeableConcept "Befund" "Befund der Mamma rechts"
* BildgebungMamma 0..* BackboneElement "Bildgebung Mamma"
  * Bildgebungsart 1..1 CodeableConcept "Art der Bildgebung" "Art der Bildgebung"
* BildgebungSonstige 0..* BackboneElement "Bildgebung Sonstige"
  * Bildgebungsart 1..1 CodeableConcept "Art der Bildgebung" "Art der Bildgebung"
* Pathologie 0..* BackboneElement "Pathologie"
  * ArtPraeparat 1..1 CodeableConcept "Befund" "Pathologischer Befund"
* Therapie 0..* BackboneElement "Therapie"
  * Operation 0..1 BackboneElement "Operation"
    * Art 1..1 CodeableConcept "Art der Operation" "Art der Operation"
    * Datum 0..1 date "Datum der Operation" "Datum der Operation"
    * Lokalisation 0..1 CodeableConcept "Lokalisation" "Lokalisation der Operation"
    * Intention 0..1 CodeableConcept "Intention" "Intent der Operation"
  * SystemischeTherapie 0..1 BackboneElement "Systemische Therapie"
    * Intention 0..1 CodeableConcept "Intention" "Intention der systemischen Therapie"
    * Startdatum 0..1 date "Startdatum" "Startdatum der systemischen Therapie"
    * Enddatum 0..1 date "Enddatum" "Enddatum der systemischen Therapie"
    * Dosis 0..1 CodeableConcept "Dosis" "Dosis der systemischen Therapie"
    * Einheit 0..1 CodeableConcept "Einheit" "Einheit der systemischen Therapie"
    * Substanz 0..1 CodeableConcept "Substanz" "Substanz der systemischen Therapie"
  * Strahlentherapie 0..1 BackboneElement "Strahlentherapie"
    * Intention 0..1 CodeableConcept "Intention" "Intention der Strahlentherapie"
    * Startdatum 0..1 date "Startdatum" "Startdatum der Strahlentherapie"
    * Enddatum 0..1 date "Enddatum" "Enddatum der Strahlentherapie"
    * Dosis 0..1 CodeableConcept "Dosis" "Dosis der Strahlentherapie"
    * Einheit 0..1 CodeableConcept "Einheit" "Einheit der Strahlentherapie"
* OperationsPlanung 0..1 BackboneElement "Operationsplanung"
  * Operationsdatum 0..1 date "Operationsdatum" "Datum der geplanten Operation"
* WeitereTermine 0..* BackboneElement "Weitere Termine"
  * Termin 1..1 date "Termin" "Datum des Termins"
* Tumorkonferenz 0..* BackboneElement "Tumorkonferenz"
  * Datum 1..1 date "Datum" "Datum der Tumorkonferenz"
  * Ort 0..1 CodeableConcept "Ort" "Ort der Tumorkonferenz"
  * EmpfehlungTumorkonferenz 0..* BackboneElement "Empfehlung" "Empfehlung der Tumorkonferenz"
    * EmpfehlungText 0..1 string "Empfehlungstext" "Text der Empfehlung der Tumorkonferenz"
    * Therapieempfehlung 0..* CodeableConcept "Therapieempfehlung" "Therapieempfehlung der Tumorkonferenz"
    * DiagnostischeEmpfehlung 0..* CodeableConcept "Diagnostische Empfehlung" "Diagnostische Empfehlung der Tumorkonferenz"
    * Studienempfehlung 0..* CodeableConcept "Studienempfehlung" "Studienempfehlung der Tumorkonferenz"
    * VorsorgeNachsorgeEmpfehlung 0..* CodeableConcept "Vorsorge- und Nachsorgeempfehlung" "Vorsorge- und Nachsorgeempfehlung der Tumorkonferenz"
    * Wiedervorstellung 0..1 date "Wiedervorstellung" "Datum der Wiedervorstellung"


    

/*
Mapping: MolGen-LogicalModel
Id: FHIR
Title: "MolGen LogicalModel FHIR Mapping"
Source: MII_LM_MolGen_LogicalModel
* Probeninformation
  * Patient -> "Patient"
  * Probe -> "Specimen"
* Anforderung -> "ServiceRequest"
  * Indikation
  * Indikation
    * Indikation -> "ServiceRequest.reasonCode"
    * Indikation -> "ServiceRequest.reasonReference"
    * Gesundheitszustand -> "ServiceRequest.supportingInfo"
    * Krankengeschichte-Familie -> "FamilyMemberHistory"
    * Anlagetraeger -> "FamilyMemberHistory" 
    * Anlagetraeger -> "Condition"
    * Anlagetraeger -> "Observation"
    * RelevanteVorergebnisse -> "Condition" 
    * RelevanteVorergebnisse -> "Observation" 
    * RelevanteVorergebnisse -> "DiagnosticReport"
    * RelevanteVorergebnisse -> "DocumentReference"
  * Anforderer -> "Practitioner" 
  * Anforderer -> "PractitionerRole" 
  * Anforderer -> "Organization"
    * Zu-testende-Gene -> "ServiceRequest.code"
    * Einheitlicher-Bewertungsmassstab -> "ChargeItem"
    * Anforderungstext -> "ServiceRequest.code.text"
  * Datum-der-Anforderung -> "ServiceRequest.authoredOn"
  * Bemerkungen -> "ServiceRequest.note"
* Methoden
  * Methode -> "Observation.method"
  * Relevante-Parameter -> "Observation" 
  * Relevante-Parameter -> "DocumentReference"
  * Geraete-Software-Kits -> "Device"
  * Getestete-Gene -> "Observation.component:gene-studied"
  * Referenzsequenz -> "Observation.component:transcript-ref-seq"
  * Read-Depth-Coverage -> "Observation.component:allelic-read-depth"
  * Intron-Spanning-IVS -> "Observation.component:dna-region" 
  * Start-und-Endnukleotid -> "Observation.component:exact-start-end"
  * Sensitivitaet-Detektionslimit -> "Observation.component:detection-limit"
  * Limitierungen-Bemerkungen -> "Observation.note"
* Ergebnisse
  * Zusammenfassung -> "Observation.valueCodeableConcept"
  * Veraenderungen 
    * Veraenderung-Proteinebene -> "Observation.component:protein-hgvs"
    * DNA-Veraenderungen -> "Observation.component:coding-hgvs"
    * Genomische-DNA-Veraenderung -> "Observation.component:genomic-hgvs"
    * Transkript-ID -> "Observation.component:transcript-ref-seq"
    * Referenzgenom -> "Observation.component:reference-sequence-assembly"
    * Ref-Allel -> "Observation.component:ref-allele"
    * Alt-Allel -> "Observation.component:alt-allele"
    * DNA-Mutationstyp -> "Observation.component:coding-change-type"
    * Mutationskonsequenz-Funktionell -> "Observation.component:amino-acid-change-type"
    * Proben-Allelfrequenz -> "Observation.component:sample-allelic-frequency"
    * Ursprung-der-Variante -> "Observation.component:genomic-source-class"
    * Varianten-ID -> "Observation.component:variation-code"
    * Chromosom -> "Observation.component:chromosome-identifier"
    * Exon -> "Observation.component:dna-region"
    * Zytogenetische-Lokalisation -> "Observation.component:cytogenetic-location"
    * Kopienzahlvariationen -> "Observation.component:copy-number"
  * Mutationslast -> "Observation.valueQuantity"
  * Mikrosatelliteninstabilität -> "Observation.valueCodeableConcept"
  * Daten -> "DocumentReference"
* Interpretation 
  * Klinische-Signifikanz -> "Observation.component:clinical-significance"
  * Referenzen -> "RelatedArtifact"
  * ClinicalAnnotationLevelOfEvidence -> "Observation.component:evidence-level"
  * Assoziierter-Phaenotyp -> "Observation.component:predicted-phenotype"
  * Assoziierter-Phaenotyp -> "Observation.component:phenotypic-treatment-context"
  * Vererbungsmodus -> "Observation.component:mode-of-inheritance"
  * Zusammenfassung -> "Observation.component:conclusion-string"
  * Empfehlungen -> "Task.code"
  * Medikationsempfehlung -> "Task.code"
* Weiteres 
  * Bericht-ID -> "DiagnosticReport.identifier"
  * Anhaenge -> "Media" 
  * Anhaenge -> "DocumentReference"
  * Berichtstatus -> "DiagnosticReport.status"
  * Datum-des-Berichts -> "DiagnosticReport.issued"
  * Labor-Institution-Ansprechpartner -> "Practitioner"
  * Labor-Institution-Ansprechpartner -> "Organization"
  * Labor-Institution-Ansprechpartner -> "PractitionerRole"
    * Laborakkreditierungen -> "Practitioner.qualification" 
    * Name-Ansprechpartner -> "Practitioner.name"
    * Adresse -> "Practitioner.address"
    * Kontakt -> "Practitioner.telecom"
*/