// =============================================================================
// OncoBox Brust 2.0 (Auditjahr 2026 v2.1.1) — Logical Model
//
// Generiert aus oncobox-brust-2.0.xsd via scripts/extractions/xsd-to-fsh.py.
// XSD-Quelle: https://xml-oncobox.de/de/Home/FuerHersteller
//
// Bildet die XML-Struktur der OncoBox-Brust-Meldung 2.0 (Auditjahr 2026) ab,
// wie sie an OnkoZert/DKG uebermittelt wird. Ersetzt das aeltere 1.0 (N1.1.1).
//
// Hauptunterschiede 1.0 → 2.0:
//   - Wurzel: <OncoBoxBrust> (statt <oncobox-brust-meldung>)
//   - <ImportInfo> statt <InfoXML>
//   - Patienten/Faelle sind jetzt 1..n explizit (Mengen)
//   - <Anamnese>, <Tumorkonferenz>, <Histologie>, <Operation>,
//     <Strahlentherapie>, <Systemtherapie>, <Fernmetastase>, <Studie>,
//     <Psychosozial>, <Follow_Up> als eigene Backbone-Elemente
//   - ER/PR getrennt: HormonrezeptorStatus_X, Anteil_positiv_X, IRS_X
//   - BRCA1/2/PALB2: Keimbahn (Anamnese) vs. somatisch (Histologie) getrennt
// =============================================================================

Logical: OncoBoxBrustMeldung
Id: oncobox-brust-meldung
Title: "OncoBox Brust 2.0 Meldung (Logical Model)"
Description: "OncoBox Brust 2.0 (Auditjahr 2026 v2.1.1) Meldungsstruktur — generiert aus dem offiziellen XSD."

* ^status = #draft
* ^version = "2.1.1"

* ImportInfo 1..1 BackboneElement "ImportInfo"
  * DatumXML 1..1 string "DatumXML"
  * NameTudokusys 1..1 string "NameTudokusys"
  * VersionTudokusys 1..1 string "VersionTudokusys"
* Patienten 1..1 BackboneElement "Patienten"
  * Patient 1..* BackboneElement "Patient"
    * Stammdaten 1..1 BackboneElement "Stammdaten"
      * OncoBoxID 1..1 string "OncoBoxID"
      * Geburtsjahr 1..1 string "Geburtsjahr"
      * Geschlecht 1..1 string "Geschlecht"
      * Versicherungsform 1..1 string "Versicherungsform"
      * Sterbedatum 1..1 string "Sterbedatum"
      * Tod_tumorbedingt 1..1 string "Tod tumorbedingt"
      * Todesursache_ICD 1..1 string "Todesursache ICD"
      * Todesursache_ICD_Version 1..1 string "Todesursache ICD Version"
    * Fall 1..* BackboneElement "Fall"
      * Fallinformation 1..1 BackboneElement "Fallinformation"
        * FallID 1..1 string "FallID"
        * Falldokumentation 1..1 string "Falldokumentation"
        * KommentarFall 1..1 string "KommentarFall"
      * Anamnese 1..1 BackboneElement "Anamnese"
        * Krebsvorerkrankungen 1..1 string "Krebsvorerkrankungen"
        * KomorbiditaetenVorDiagnose 1..1 string "KomorbiditaetenVorDiagnose"
        * RaucherStatus 1..1 string "RaucherStatus"
        * Praetherapeutischer_Menopausenstatus 1..1 string "Praetherapeutischer Menopausenstatus"
        * BRCA1_Keimbahn 1..1 string "BRCA1 Keimbahn"
        * BRCA2_Keimbahn 1..1 string "BRCA2 Keimbahn"
        * PALB2_Keimbahn 1..1 string "PALB2 Keimbahn"
      * Diagnose 1..1 BackboneElement "Diagnose"
        * Zertifizierung 1..1 string "Zertifizierung"
        * Tumormanifestation 1..1 string "Tumormanifestation"
        * Seitenlokalisation 1..1 string "Seitenlokalisation"
        * Version 1..1 string "Version"
        * ICD_10 1..1 string "ICD 10"
        * ICD_11 1..1 string "ICD 11"
        * SynchroneBehandlung 1..1 string "SynchroneBehandlung"
        * Diagnosedatum 1..1 string "Diagnosedatum"
        * Alter 1..1 string "Alter"
        * Allgemeiner_Leistungszustand 1..1 string "Allgemeiner Leistungszustand"
        * Praeth_T_c_p 1..1 string "Praeth T c p"
        * Praeth_T 1..1 string "Praeth T"
        * Praeth_N_c_p 1..1 string "Praeth N c p"
        * Praeth_N 1..1 string "Praeth N"
        * Praeth_M_c_p 1..1 string "Praeth M c p"
        * Praeth_M 1..1 string "Praeth M"
        * y_Symbol 1..1 string "y Symbol"
        * Postop_T_c_p 1..1 string "Postop T c p"
        * Postop_T 1..1 string "Postop T"
        * Postop_N_c_p 1..1 string "Postop N c p"
        * Postop_N 1..1 string "Postop N"
        * Postop_M_c_p 1..1 string "Postop M c p"
        * Postop_M 1..1 string "Postop M"
        * Checkliste 1..1 string "Checkliste"
        * Checkliste_Score 1..1 string "Checkliste Score"
        * Gesamtbeurteilung_Residualstatus 1..1 string "Gesamtbeurteilung Residualstatus"
        * Gesamtbeurteilung_Tumorstatus 1..1 string "Gesamtbeurteilung Tumorstatus"
      * Tumorkonferenz 1..* BackboneElement "Tumorkonferenz"
        * Tumorkonferenz_Datum 1..1 string "Tumorkonferenz Datum"
        * Tumorkonferenz_Typ 1..1 string "Tumorkonferenz Typ"
        * Empfehlung_Therapie 1..1 string "Empfehlung Therapie"
        * Empfehlung_Trastuzumab 1..1 string "Empfehlung Trastuzumab"
      * Histologie 1..* BackboneElement "Histologie"
        * Praeparat 1..1 string "Praeparat"
        * Biopsieart 1..1 string "Biopsieart"
        * Tumor_Histologiedatum 1..1 string "Tumor Histologiedatum"
        * Tumortyp 1..1 string "Tumortyp"
        * Grading 1..1 string "Grading"
        * Lokale_Beurteilung_Residualstatus 1..1 string "Lokale Beurteilung Residualstatus"
        * HormonrezeptorStatus_Oestrogen 1..1 string "HormonrezeptorStatus Oestrogen"
        * Anteil_positiv_Oestrogen 1..1 string "Anteil positiv Oestrogen"
        * IRS_Oestrogen 1..1 string "IRS Oestrogen"
        * HormonrezeptorStatus_Progesteron 1..1 string "HormonrezeptorStatus Progesteron"
        * Anteil_positiv_Progesteron 1..1 string "Anteil positiv Progesteron"
        * IRS_Progesteron 1..1 string "IRS Progesteron"
        * Her2neuStatus 1..1 string "Her2neuStatus"
        * Ki_67 1..1 string "Ki 67"
        * PD_L1 1..1 string "PD L1"
        * BRCA1_somatisch 1..1 string "BRCA1 somatisch"
        * BRCA2_somatisch 1..1 string "BRCA2 somatisch"
        * PALB2_somatisch 1..1 string "PALB2 somatisch"
        * LK_untersucht 1..1 string "LK untersucht"
        * LK_befallen 1..1 string "LK befallen"
        * Sentinel_LK_untersucht 1..1 string "Sentinel LK untersucht"
        * Sentinel_LK_befallen 1..1 string "Sentinel LK befallen"
      * Operation 1..* BackboneElement "Operation"
        * OP_Datum 1..1 string "OP Datum"
        * OP_Intention 1..1 string "OP Intention"
        * OPS 1..1 string "OPS"
        * PraeopMarkierung 1..1 string "PraeopMarkierung"
        * IntraopPraeparatkontrolle 1..1 string "IntraopPraeparatkontrolle"
        * OP_Komplikationen_Art 1..1 string "OP Komplikationen Art"
        * OP_Komplikationen_Zeitpunkt 1..1 string "OP Komplikationen Zeitpunkt"
        * Erstoperateur 1..1 string "Erstoperateur"
        * Zweitoperateur 1..1 string "Zweitoperateur"
      * Strahlentherapie 1..* BackboneElement "Strahlentherapie"
        * Strahlentherapie_Beginn 1..1 string "Strahlentherapie Beginn"
        * Strahlentherapie_Ende 1..1 string "Strahlentherapie Ende"
        * Radiochemotherapie 1..1 string "Radiochemotherapie"
        * Strahlentherapie_Applikationsart 1..1 string "Strahlentherapie Applikationsart"
        * Strahlentherapie_Zielgebiet 1..1 string "Strahlentherapie Zielgebiet"
        * Strahlentherapie_Seite_Zielgebiet 1..1 string "Strahlentherapie Seite Zielgebiet"
        * Strahlentherapie_Intention 1..1 string "Strahlentherapie Intention"
        * Strahlentherapie_Stellung_OP 1..1 string "Strahlentherapie Stellung OP"
        * Strahlentherapie_Gesamtdosis 1..1 string "Strahlentherapie Gesamtdosis"
        * Strahlentherapie_Einzeldosis 1..1 string "Strahlentherapie Einzeldosis"
        * Strahlentherapie_Boost 1..1 string "Strahlentherapie Boost"
      * Systemtherapie 1..* BackboneElement "Systemtherapie"
        * Systemtherapie_Therapieart 1..1 string "Systemtherapie Therapieart"
        * Therapielinie 1..1 string "Therapielinie"
        * Systemtherapie_Beginn 1..1 string "Systemtherapie Beginn"
        * Systemtherapie_Ende 1..1 string "Systemtherapie Ende"
        * Systemtherapie_Intention 1..1 string "Systemtherapie Intention"
        * Systemtherapie_Stellung_OP 1..1 string "Systemtherapie Stellung OP"
        * CHT_Substanzen 1..1 string "CHT Substanzen"
        * Sonstige_CHT_Substanzen 1..1 string "Sonstige CHT Substanzen"
        * HO_Substanzen 1..1 string "HO Substanzen"
        * Sonstige_HO_Substanzen 1..1 string "Sonstige HO Substanzen"
        * IM_Substanzen 1..1 string "IM Substanzen"
        * Sonstige_IM_Substanzen 1..1 string "Sonstige IM Substanzen"
        * Zielgerichtete_Substanzen 1..1 string "Zielgerichtete Substanzen"
        * Sonstige_Zielgerichtete_Substanzen 1..1 string "Sonstige Zielgerichtete Substanzen"
        * Nebenwirkung_Typ 1..1 string "Nebenwirkung Typ"
      * Fernmetastase 1..* BackboneElement "Fernmetastase"
        * Fernmetastase_Lokalisation 1..1 string "Fernmetastase Lokalisation"
        * Fernmetastase_Diagnosedatum 1..1 string "Fernmetastase Diagnosedatum"
        * Fernmetastase_OP_Datum 1..1 string "Fernmetastase OP Datum"
        * Fernmetastase_Therapie 1..1 string "Fernmetastase Therapie"
        * Fernmetastase_lokaler_Residualstatus 1..1 string "Fernmetastase lokaler Residualstatus"
      * Studie 1..* BackboneElement "Studie"
        * Studienname 1..1 string "Studienname"
        * Studienname_Selektiv 1..1 string "Studienname Selektiv"
        * ScreeningStudienteilnahme 1..1 string "ScreeningStudienteilnahme"
        * Studienteilnahme 1..1 string "Studienteilnahme"
      * Psychosozial 1..1 BackboneElement "Psychosozial"
        * DistressScreening 1..1 string "DistressScreening"
        * Sozialdienstkontakt 1..1 string "Sozialdienstkontakt"
      * Follow_Up 1..* BackboneElement "Follow Up"
        * Meldedatum 1..1 string "Meldedatum"
        * Follow_Up_Melder 1..1 string "Follow Up Melder"
        * Untersuchungsdatum_Verlauf 1..1 string "Untersuchungsdatum Verlauf"
        * Follow_Up_Aktiv_Passiv 1..1 string "Follow Up Aktiv Passiv"
        * Vitalstatus 1..1 string "Vitalstatus"
        * Gesamtbeurteilung_Tumorstatus 1..1 string "Gesamtbeurteilung Tumorstatus"
        * Verlauf_Lokaler_Tumorstatus 1..1 string "Verlauf Lokaler Tumorstatus"
        * Verlauf_Tumorstatus_Lymphknoten 1..1 string "Verlauf Tumorstatus Lymphknoten"
        * Verlauf_Tumorstatus_Fernmetastasen 1..1 string "Verlauf Tumorstatus Fernmetastasen"
        * Zweittumor 1..1 string "Zweittumor"
