<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="AntikoagulansAortenklappeBasis">	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>	<xs:annotation>		<xs:documentation>			Dieses Schema beschreibt die Elemente des Bausteins AntikoagulansAortenklappeBasis. 			Es handelt sich um die Antikoagulation-spezifische Angabe, welche postprozedural vorgenommen wurde.			Elemente:			- AKA_AntikoagulansSchluessel: Antikoagulation (bei Entlassung)		</xs:documentation>	</xs:annotation>	<xs:complexType name="AntikoagulansAortenklappeBasis">		<xs:sequence>			<xs:element name="AKA_AntikoagulansSchluessel" type="enum_0389"/>		</xs:sequence>	</xs:complexType></xs:schema>