<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="Artikelidentifikation">
	<xs:include schemaLocation="./ArtikelidentifikationBasis.xsd"/>
	<xs:include schemaLocation="./Artikelbeschreibung.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt den Aufbau des Bausteins Artikelidentifikation, welche aus Schemas "ArtikelidentifikationBasis", und	"Artikelbeschreibung" besteht.
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="Artikelidentifikation">
		<xs:complexContent>
			<xs:extension base="ArtikelidentifikationBasis">
				<xs:sequence>
					<xs:element name="artikelbeschreibung" type="Artikelbeschreibung"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>