<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="AusloeserBasis">	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>	<xs:annotation>		<xs:documentation>			Dieses Schema beschreibt die Elemente des Bausteins AusloeserBasis. 			Es handelt sich um die eine Meldung an das Implantateregister auslösenden Operationen- und Prozedurenschlüssel.			Elemente:			- ALR_ProzedurenSchluessel: OPS-Kode		</xs:documentation>	</xs:annotation>	<xs:complexType name="AusloeserBasis">		<xs:sequence>			<xs:element name="ALR_ProzedurenSchluessel" type="OPS"/>		</xs:sequence>	</xs:complexType></xs:schema>