<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="BefundBrustimplantatBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins BefundBrustimplantatBasis. 
			Elemente:
			- BEB_BefundSchluessel: Befund bei einer Revision / Explantation
			- BEB_BefundAustauschSchluessel: Befund bei Austausch Expander gegen Implantat
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="BefundBrustimplantatBasis">
		<xs:sequence>
			<xs:choice>
				<xs:element name="BEB_BefundSchluessel" type="enum_0121"/>
				<xs:element name="BEB_BefundAustauschSchluessel" type="enum_0120"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
</xs:schema>