<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="DiagnoseBrustimplantatBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins DiagnoseBrustimplantatBasis
			Es handelt sich um die Brustimplantat-spezifische Diagnose, mit der die Patientin bzw. der Patient aus der Gesundheitseinrichtung
			entlassen wird.
			Elemente:
			- DBI_IcdSchluessel: Entlassungsdiagnose
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="DiagnoseBrustimplantatBasis">
		<xs:sequence>
			<xs:element name="DBI_IcdSchluessel" type="ICD"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>