<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="EmpfangsbestaetigungBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins EmpfangsbestaetigungBasis. 
			Elemente:
			- EBG_Empfangsbestaetigung: Formale Bestätigung des Eingangs der Meldung bei der Registerstelle
			- EBG_DatumZeitEmpfang: Zeitstempel der Ausstellung der Empfangsbestätigung
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="EmpfangsbestaetigungBasis">
		<xs:sequence>
			<xs:element name="EBG_Empfangsbestaetigung" type="Freitext250" fixed="Hiermit wird der Eingang Ihrer Anfrage bestätigt"/>
			<xs:element name="EBG_DatumZeitEmpfang" type="xs:dateTime"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>