<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="EntlassungBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins EntlassungBasis. 
			Es handelt sich um organisatorische und medizinische Daten zur Patientin bzw. zum Patienten, die bei der Entlassung erhoben
			 wurden. Die Entlassungsdiagnosen werden in den untergeordneten Bausteinen angegeben.
			Elemente:
			- ENT_Datum: Entlassungsdatum
			- ENT_GrundSchluessel: Entlassungs-/Verlegungsgrund
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="EntlassungBasis">
		<xs:sequence>
			<xs:element name="ENT_Datum" type="xs:date"/>
			<xs:element name="ENT_GrundSchluessel" type="String2" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>