<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="FailureGrundAortenklappeBasis">	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>	<xs:annotation>		<xs:documentation>			Dieses Schema beschreibt die Elemente des Bausteins FailureGrundAortenklappeBasis. 			Es handelt sich um die Aortenklappe-spezifischen Operationsschlüssel, die dem jeweiligen operativen Eingriff zugeordnet werden.			Elemente:			- FAK_FailureGrundSchluessel: Grund für Technical Success = nein		</xs:documentation>	</xs:annotation>	<xs:complexType name="FailureGrundAortenklappeBasis">		<xs:sequence>			<xs:element name="FAK_FailureGrundSchluessel" type="enum_0341"/>		</xs:sequence>	</xs:complexType></xs:schema>