<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="FallBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins FallBasis. 
			Es handelt sich um technische-organisatorische Daten und allgemeine Daten zum Versorgungsprozess. Weitere, insbesondere klinische Daten zum
			Fall werden in untergeordneten Bausteinen angegeben.
			Elemente:
			- FAL_Aufnahmedatum: Aufnahmedatum
			- FAL_ArtAufenthaltSchluessel: Art des Aufenthalts
			- FAL_Transfernummer: Transfernummer, die die Gesundheitseinrichtung von der Vertrauensstelle erhält
			- FAL_DatumZeitSatzErstellung: Zeitstempel der Erstellung des Datensatzes
			- FAL_Versionsnummer: Version des gelieferten Falls
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="FallBasis">
		<xs:sequence>
			<xs:element name="FAL_Aufnahmedatum" type="xs:date"/>
			<xs:element name="FAL_ArtAufenthaltSchluessel" type="enum_0065"/>
			<xs:element name="FAL_Transfernummer" type="Transfernummer"/>
			<xs:element name="FAL_DatumZeitSatzErstellung" type="xs:dateTime"/>
			<xs:element name="FAL_Versionsnummer" type="Versionsnummer" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>