<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="HinweisBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins HinweisBasis. 
			Elemente:
			- HNW_Datenelement: Warnung oder Fehler im Datenelement:
			- HNW_Meldung: Warn- oder Fehlermeldung
			- HNW_Wert: Wert des Datenelements
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="HinweisBasis">
		<xs:sequence>
			<xs:element name="HNW_Datenelement" type="Freitext500"/>
			<xs:element name="HNW_Meldung" type="Freitext500"/>
			<xs:element name="HNW_Wert" type="Freitext500"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>