<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="InfektionAortenklappeBasis">	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>	<xs:annotation>		<xs:documentation>			Dieses Schema beschreibt die Elemente des Bausteins InfektionAortenklappeBasis. 			Es handelt sich um die Aortenklappen-spezifischen Infektionsschlüssel, die dem jeweiligen operativen Eingriff zugeordnet werden.			Elemente:			- IAK_InfektionSchluessel: akute Infektion(en)		</xs:documentation>	</xs:annotation>	<xs:complexType name="InfektionAortenklappeBasis">		<xs:sequence>			<xs:element name="IAK_InfektionSchluessel" type="enum_0367"/>		</xs:sequence>	</xs:complexType></xs:schema>