<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="KomplikationAortenklappeBasis">	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>	<xs:annotation>		<xs:documentation>			Dieses Schema beschreibt die Elemente des Bausteins KomplikationAortenklappeBasis. 			Es handelt sich um die Aortenklappe-spezifischen Operationen- und Prozedurenschlüssel, die dem jeweiligen operativen Eingriff zugeordnet werden.			Elemente:			- KAK_KomplikationTypSchluessel: Typ einer intraprozeduralen Komplikation		</xs:documentation>	</xs:annotation>	<xs:complexType name="KomplikationAortenklappeBasis">		<xs:sequence>			<xs:element name="KAK_KomplikationTypSchluessel" type="enum_0343"/>		</xs:sequence>	</xs:complexType></xs:schema>