<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="MassnahmeBrustimplantatBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins MassnahmeBrustimplantatBasis. 
			Es handelt sich um Brustimplantat-spezifische Maßnahmen, die im Rahmen des jeweiligen operativen Eingriffs durchgeführt werden.
			Elemente:
			- MAB_MassnahmeSchluessel: Operationsmaßnahme
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="MassnahmeBrustimplantatBasis">
		<xs:sequence>
			<xs:element name="MAB_MassnahmeSchluessel" type="enum_0116"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>