<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="MeldungIrdBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt das Teilelement des Bausteins MeldungIrdBasis für Antwortenarten und Storno.
			Elemente:
			- MEL_IrdIdGesundheitseinrichtung: Kennzeichen der Gesundheitseinrichtung
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="MeldungIrdBasis">
		<xs:sequence>
			<xs:element name="MEL_IrdIdGesundheitseinrichtung" type="IdEinrichtung"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>