<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="MeldungIrdFallBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Teilelemente des Bausteins MeldungIrdFallBasis.
			Elemente:
			- FAL_Transfernummer: Transfernummer, die die Gesundheitseinrichtung von der Vertrauensstelle erhält
			- FAL_DatumZeitSatzErstellung: Zeitstempel der Erstellung des Datensatzes
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="MeldungIrdFallBasis">
		<xs:sequence>
			<xs:element name="FAL_Transfernummer" type="Transfernummer"/>
			<xs:element name="FAL_DatumZeitSatzErstellung" type="xs:dateTime"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>