<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="MeldungIrd">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:include schemaLocation="./MeldungIrdBasis.xsd"/>
	<xs:include schemaLocation="./MeldungIrdFallBasis.xsd"/>
	
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt den Aufbau des Bausteins MeldungIrd, welcher aus dem Schema "MeldungIrdBasis" und "MeldungIrdFallBasis" besteht.
		</xs:documentation>
	</xs:annotation>

	<xs:complexType name="MeldungIrd">
		<xs:complexContent>
			<xs:extension base="MeldungIrdBasis">
				<xs:sequence>
					<xs:element name="fall" type="MeldungIrdFallBasis"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>