<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="OperationBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins OperationBasis.
			Es handelt sich um Daten, die sich direkt auf den operativen Eingriff beziehen. Werden während eines Aufenthalts in der Gesundheitseinrichtung mehrere operative Eingriffe durchgeführt, so kommt der Baustein Operation in einem Fall mehrfach vor.
			Elemente:
			- OPE_LaufendeNummer: Sequenz der Operation 
			- OPE_Datum: Operationsdatum
			- OPE_SeitenLokalisationSchluessel: Seitenlokalisation dieses Eingriffs
			- OPE_AsaSchluessel: ASA-Klassifikation
			- OPE_ImplantattypSchluessel: Implantattyp			
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="OperationBasis">
		<xs:sequence>
			<xs:element name="OPE_LaufendeNummer" type="Zahl3"/>
			<xs:element name="OPE_Datum" type="xs:date"/>
			<xs:element name="OPE_SeitenLokalisationSchluessel" type="enum_0050" minOccurs="0"/>
			<xs:element name="OPE_AsaSchluessel" type="enum_0044"/>
			<xs:element name="OPE_ImplantattypSchluessel" type="enum_0080"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>