<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="OperationEndoprothese">

	<xs:include schemaLocation="./OperationEndoprotheseBasis.xsd"/>
	<xs:include schemaLocation="./VorbehandlungEndoprotheseBasis.xsd"/>
	<xs:include schemaLocation="./ProzedurenSchluesselEndoprotheseBasis.xsd"/>
	
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins OperationEndoprothese, welcher aus den Schemas "OperationEndoprotheseBasis", "VorbehandlungEndoprotheseBasis" und "ProzedurenSchluesselEndoprotheseBasis" besteht. 
		</xs:documentation>
	</xs:annotation>

	<xs:complexType name="OperationEndoprothese">
		<xs:complexContent>
			<xs:extension base="OperationEndoprotheseBasis">
				<xs:sequence>
					<xs:element name="vorbehandlungEndoprothese" type="VorbehandlungEndoprotheseBasis" minOccurs="0"/>
					<xs:element name="prozedurenSchluesselEndoprothese" type="ProzedurenSchluesselEndoprotheseBasis" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>
