<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="OperationBrustimplantat">

	<xs:include schemaLocation="./OperationBrustimplantatBasis.xsd"/>
	<xs:include schemaLocation="./VorbehandlungBrustimplantatBasis.xsd"/>
	<xs:include schemaLocation="./MassnahmeBrustimplantatBasis.xsd"/>
	<xs:include schemaLocation="./OperationsdetailBrustimplantatBasis.xsd"/>
	<xs:include schemaLocation="./BefundBrustimplantatBasis.xsd"/>
	<xs:include schemaLocation="./ProzedurenSchluesselBrustimplantatBasis.xsd"/>
	
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins OperationBrustimplantat, welcher aus den Schemas "OperationBrustimplantatBasis", "VorbehandlungBrustimplantatBasis", "MassnahmeBrustimplantat", "OperationsdetailBrustimplantat", "BefundBrustimplantat" und "ProzedurenSchluesselBrustimplantatBasis" besteht. 
		</xs:documentation>
	</xs:annotation>

	<xs:complexType name="OperationBrustimplantat">
		<xs:complexContent>
			<xs:extension base="OperationBrustimplantatBasis">
				<xs:sequence>
					<xs:element name="vorbehandlungBrustimplantat" type="VorbehandlungBrustimplantatBasis" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="massnahmeBrustimplantat" type="MassnahmeBrustimplantatBasis" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="operationsdetailBrustimplantat" type="OperationsdetailBrustimplantatBasis" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="befundBrustimplantat" type="BefundBrustimplantatBasis" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="prozedurenSchluesselBrustimplantat" type="ProzedurenSchluesselBrustimplantatBasis" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>
