<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="OperationAortenklappe">

	<xs:include schemaLocation="./OperationAortenklappeBasis.xsd"/>
	<xs:include schemaLocation="./TaviAortenklappeBasis.xsd"/>
	<xs:include schemaLocation="./ProzedurenSchluesselAortenklappeBasis.xsd"/>
	<xs:include schemaLocation="./FailureGrundAortenklappeBasis.xsd"/>
	<xs:include schemaLocation="./PciAortenklappeBasis.xsd"/>
	<xs:include schemaLocation="./KomplikationAortenklappeBasis.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins OperationAortenklappe, welcher aus den Schemas "OperationAortenklappeBasis", "TaviAortenklappeBasis", "ProzedurenSchluesselAortenklappeBasis", "FailureGrundAortenklappeBasis" und "PciAortenklappeBasis" besteht. 
		</xs:documentation>
	</xs:annotation>

	<xs:complexType name="OperationAortenklappe">
		<xs:complexContent>
			<xs:extension base="OperationAortenklappeBasis">
				<xs:sequence>
					<xs:element name="komplikationAortenklappe" type="KomplikationAortenklappeBasis" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="taviAortenklappe" type="TaviAortenklappeBasis" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="pciAortenklappe" type="PciAortenklappeBasis" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="failureGrundAortenklappe" type="FailureGrundAortenklappeBasis" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="prozedurenSchluesselAortenklappe" type="ProzedurenSchluesselAortenklappeBasis" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>
