<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="OperationsdetailBrustimplantatBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins OperationsdetailBrustimplantatBasis. 
			Es handelt sich um Brustimplantat-spezifische Details zum operativen Eingriff.
			Elemente:
			- ODB_OperationsdetailPrimaerEingriffSchluessel: Operationsdetail Primäreingriff
			- ODB_OperationsdetailAustauschSchluessel: Operationsdetail Austausch
			- ODB_OperationsdetailRevisionSchluessel: Operationsdetail Revision
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="OperationsdetailBrustimplantatBasis">
		<xs:sequence>
			<xs:choice>
				<xs:element name="ODB_OperationsdetailPrimaerEingriffSchluessel" type="enum_0103"/>
				<xs:element name="ODB_OperationsdetailAustauschSchluessel" type="enum_0105"/>
				<xs:element name="ODB_OperationsdetailRevisionSchluessel" type="enum_0107"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
</xs:schema>