<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="OperationBrustimplantatBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins OperationBrustimplantatBasis. 
			Es handelt sich um Brustimplantat-spezifische Angaben zum jeweiligen operativen Eingriff.
			Elemente:
			- OBI_ArtEingriffSchluessel: Art dieses Eingriffs
			- OBI_GrundPrimaerEingriffSchluessel: Grund dieses Primäreingriffs
			- OBI_GrundAustauschSchluessel: Grund dieser Revision
			- OBI_GrundRevisionExplantationSchluessel: Grund dieser Explantation
			- OBI_LageSchluessel: Lage des neuen Implantats
			- OBI_ZugangSchluessel: Operationszugang
			- OBI_EntfernungAdmNetzSchluessel: Entfernung des ADM/Netzes
			- OBI_VerfahrenswechselSchluessel: Verfahrenswechsel
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="OperationBrustimplantatBasis">
		<xs:sequence>
			<xs:element name="OBI_ArtEingriffSchluessel" type="enum_0100"/>
			<xs:choice>
				<xs:element name="OBI_GrundPrimaerEingriffSchluessel" type="enum_0102"/>
				<xs:element name="OBI_GrundAustauschSchluessel" type="enum_0104"/>
				<xs:element name="OBI_GrundRevisionExplantationSchluessel" type="enum_0106"/>
			</xs:choice>
			<xs:element name="OBI_LageSchluessel" type="enum_0112" minOccurs="0"/>
			<xs:element name="OBI_ZugangSchluessel" type="enum_0118" minOccurs="0"/>
			<xs:element name="OBI_EntfernungAdmNetzSchluessel" type="enum_0114" minOccurs="0"/>
			<xs:element name="OBI_VerfahrenswechselSchluessel" type="enum_0111" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>