<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="OperationEndoprotheseBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins OperationEndoprotheseBasis. 
			Es handelt sich um Endoprothesen-spezifische Angaben zum jeweiligen operativen Eingriff.
			Elemente:
			- OEP_ArtEingriffSchluessel: Art dieses Eingriffs
			- OEP_GelenkSchluessel: Operiertes Gelenk
			- OEP_DringlichkeitSchluessel: Dringlichkeit dieses Eingriffs
			- OEP_FrakturJNSchluessel: Fraktur Ja/ Nein
			- OEP_ZweizeitwechselSchluessel: Zweitzeitiger Wechsel
			- OEP_GrundWechselKnieSchluessel: Wechselgrund Knie
			- OEP_GrundWechselHuefteSchluessel: Wechselgrund Hüfte
			- OEP_GrundWechselTfeSchluessel: Wechselgrund Totaler Femurersatz
			- OEP_GrundWechselErlaeuterung: Erläuterung Wechselgrund
			- OEP_KomponenteKnieSchluessel: Betroffene Komponenten: Lockerung/Osteolyse Knie
			- OEP_KomponenteHuefteSchluessel: Betroffene Komponenten: Lockerung/Osteolyse Hüfte
			- OEP_KomponenteTfeSchluessel: Betroffene Komponenten: Lockerung/Osteolyse TFE
			- OEP_ImplantatbruchKnieSchluessel: Betroffene Komponenten: Implantatbruch Knie
			- OEP_ImplantatbruchHuefteSchluessel: Betroffene Komponenten: Implantatbruch Hüfte
			- OEP_ImplantatbruchTfeSchluessel: Betroffene Komponenten: Implantatbruch TFE
			- OEP_VerschleissKnieSchluessel: Betroffene Komponenten: Verschleiss Knie
			- OEP_MigrationKnieSchluessel: Betroffene Komponenten: Migration/Dislokation Knie
			- OEP_ZugangHuefteSchluessel: Operationszugang Hüfte
			- OEP_EndocertJNSchluessel: Endocert-Eingriff
			- OEP_AssistiveTechnologieSchluessel: Assistive Technologie
			- OEP_NavigationSchluessel: Verwendetes Navigationssystem
			- OEP_RobotikSchluessel: Verwendetes Robotiksystem
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="OperationEndoprotheseBasis">
		<xs:sequence>
			<xs:element name="OEP_ArtEingriffSchluessel" type="enum_0200"/>
			<xs:element name="OEP_GelenkSchluessel" type="enum_0212"/>
			<xs:element name="OEP_DringlichkeitSchluessel" type="enum_0075"/>
			<xs:element name="OEP_FrakturJNSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:element name="OEP_ZweizeitwechselSchluessel" type="enum_0222" minOccurs="0"/>
			<xs:choice minOccurs="0">
				<xs:element name="OEP_GrundWechselKnieSchluessel" type="enum_0204"/>
				<xs:element name="OEP_GrundWechselHuefteSchluessel" type="enum_0202"/>
				<xs:element name="OEP_GrundWechselTfeSchluessel" type="enum_0206"/>
			</xs:choice>
			<xs:element name="OEP_GrundWechselErlaeuterung" type="Freitext250" minOccurs="0"/>
			<xs:choice minOccurs="0">
				<xs:element name="OEP_KomponenteKnieSchluessel" type="enum_0254"/>
				<xs:element name="OEP_KomponenteHuefteSchluessel" type="enum_0252"/>
				<xs:element name="OEP_KomponenteTfeSchluessel" type="enum_0256"/>
			</xs:choice>
			<xs:choice minOccurs="0">
				<xs:element name="OEP_ImplantatbruchKnieSchluessel" type="enum_0264"/>
				<xs:element name="OEP_ImplantatbruchHuefteSchluessel" type="enum_0262"/>
				<xs:element name="OEP_ImplantatbruchTfeSchluessel" type="enum_0266"/>
			</xs:choice>
			<xs:element name="OEP_VerschleissKnieSchluessel" type="enum_0270" minOccurs="0"/>
			<xs:element name="OEP_MigrationKnieSchluessel" type="enum_0271" minOccurs="0"/>
			<xs:element name="OEP_ZugangHuefteSchluessel" type="enum_0220" minOccurs="0"/>
			<xs:element name="OEP_EndocertJNSchluessel" type="enum_0060"/>
            <xs:element name="OEP_AssistiveTechnologieSchluessel" type="enum_0280"/>
			<xs:element name="OEP_NavigationSchluessel" type="enum_0281" minOccurs="0"/>
			<xs:element name="OEP_RobotikSchluessel" type="enum_0282" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>