<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="OperationAortenklappeBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins OperationAortenklappeBasis. 
			Es handelt sich um Aortenklappen-spezifische Angaben zum jeweiligen operativen Eingriff.
			Elemente:
			- OAK_NummerEingriff: Wievielter Aortenklappeneingriff während dieses Aufenthaltes?
			- OAK_ArtEingriffSchluessel: Art dieses Eingriffs
			- OAK_GrundEingriffSchluessel: Grund des Eingriffs
			- OAK_DringlichkeitSchluessel: Dringlichkeit dieses Eingriffs
			- OAK_ExplantationSchluessel: Wurde während dieses Eingriffs eine frühere Aortenklappenprothese explantiert?		
			- OAK_IsoliertSchluessel: Isolierter Aortenklappeneingriff			
			- OAK_ZugangKonventionellSchluessel: Zugangsweg (konventionell)			
			- OAK_ZugangKatheterSchluessel: Zugangsweg (kathetergestützt)		
			- OAK_KomplikationenSchluessel: intraprozedurale Komplikationen					
			- OAK_TherapieLcoSchluessel: Therapie des Low Cardiac Output			
			- OAK_Durchleuchtungszeit: Durchleuchtungszeit			
			- OAK_BeatmungSchluessel: Patient wird beatmet			
			- OAK_TroponinSchluessel: Troponin positiv (präprozedural)			
			- OAK_InotropeSchluessel: Inotrope (präprozedural)
			- OAK_Eingriffsdauer: Dauer des Eingriffs (Schnitt-Naht-Zeit)			
			- OAK_EingriffsumfangSchluessel: Umfang des Eingriffs
			- OAK_ProzedurenAnzahl: Anzahl der Prozeduren
			- OAK_VorgehenSchluessel: OP-Vorgehen
			- OAK_Bypasszeit: Bypasszeit
			- OAK_BypasszeitUnbekannt: Bypasszeit unbekannt
			- OAK_Abklemmzeit: Aortenabklemmzeit
			- OAK_AbklemmzeitUnbekannt: Aortenabklemmzeit unbekannt
			- OAK_AortaThorakalSchluessel: Eingriff an der thorakalen Aorta
			- OAK_NeuroprotektionSchluessel: Verwendung eines Systems zur Neuroprotektion
			- OAK_KreislaufunterstuetzungSchluessel: mechanische Kreislaufunterstützung
			- OAK_PraeOpUnterstuetzungSchluessel: präprozedural
			- OAK_PraeOpMethodeSchluessel: Methode (präprozedural)
			- OAK_IntraOpUnterstuetzungSchluessel: intraprozedural
			- OAK_IntraOpMethodeSchluessel: Methode (intraprozedural)
			- OAK_AortenklappenOpAnzahl: wievielte Aortenklappen-Prozedur mit diesem Zugang während dieses Aufenthaltes
			- OAK_ValveInValveSchluessel: Geplante Valve-in-Valve
			- OAK_ZugangsGefaessdiameter: Zugangsgefäßdiameter
			- OAK_ZugangsGefaessUnbekannt: Zugangsgefäßdiameter unbekannt
			- OAK_ZugangVerkalkungSchluessel: Verkalkung der Zugangsgefäße
			- OAK_Aortenklappenannulus: Aortenklappenannulus (Durchmesser)
			- OAK_MessmethodeSchluessel: Annulus-Messmethode
			- OAK_DistanzRca: Distanz Aortenklappe - Koronarien: RCA
			- OAK_DistanzRcaUnbekannt: Distanz Aortenklappe - Koronarien: RCA unbekannt
			- OAK_DistanzLca: Distanz Aortenklappe - Koronarien: LCA
			- OAK_DistanzLcaUnbekannt: Distanz Aortenklappe - Koronarien: LCA unbekannt			
			- OAK_PtcaVorSchluessel: Ballondilatation unmittelbar vor Implantation
			- OAK_PtcaVorDurchmesser: maximaler Ballondurchmesser vor Implantation	
			- OAK_PtcaVorDurchmesserUnbekannt: maximaler Ballondurchmesser vor Implantation unbekannt			
			- OAK_PtcaVorAnzahl: Anzahl Ballondilatationen vor Implantation		
			- OAK_RapidPacingVorSchluessel: rapid pacing vor Implantation
			- OAK_RapidPacingIntraSchluessel: rapid pacing zur Prothesenimplantation			
			- OAK_PtcaNachSchluessel: Ballondilatation unmittelbar nach Implantation	
			- OAK_PtcaNachDurchmesser: maximaler Ballondurchmesser nach Implantation
			- OAK_PtcaNachDurchmesserUnbekannt: maximaler Ballondurchmesser nach Implantation unbekannt
			- OAK_PtcaNachAnzahl: Anzahl Ballondilatationen nach Implantation	
			- OAK_RapidPacingNachSchluessel: rapid pacing nach Implantation				
			- OAK_KonversionSchluessel: Konversion
			- OAK_SuccessSchluessel: Technical success (nach VARC-3)
			- OAK_AnaesthesieSchluessel: Anästhesieverfahren
			- OAK_DeltaPmeanNachOp: Device Delta Pmean nach Prozedur
			- OAK_DeltaPmeanNachOpUnbekannt: Device Delta Pmean nach Prozedur nicht gemessen
			- OAK_ResidualeInsuffizienzSchluessel: residuale Aorteninsuffizienz
			- OAK_ZugangVerschlussSchluessel: Verschluss des Zugangsweges
			- OAK_ZusaetzlichePciSchluessel: zusätzliche PCI
			- OAK_PciWegenKhkSchluessel: PCI wegen KHK
			- OAK_PciWegenKomplikationSchluessel: PCI zur Behandlung von Komplikationen der Intervention
			- OAK_LaesionenAnzahl: Anzahl dilatierter Läsionen						
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="OperationAortenklappeBasis">
		<xs:sequence>
			<xs:element name="OAK_NummerEingriff" type="Zahl2"/>
			<xs:element name="OAK_ArtEingriffSchluessel" type="enum_0300"/>
			<xs:element name="OAK_GrundEingriffSchluessel" type="enum_0302"/>
			<xs:element name="OAK_DringlichkeitSchluessel" type="enum_0076"/>
			<xs:element name="OAK_ExplantationSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:element name="OAK_IsoliertSchluessel" type="enum_0060"/>
			<xs:choice>
				<xs:element name="OAK_ZugangKonventionellSchluessel" type="enum_0320"/>
				<xs:element name="OAK_ZugangKatheterSchluessel" type="enum_0318"/>
			</xs:choice>
			<xs:element name="OAK_KomplikationenSchluessel" type="enum_0060"/>
			<xs:element name="OAK_TherapieLcoSchluessel" type="enum_0346" minOccurs="0"/>
			<xs:element name="OAK_Durchleuchtungszeit" type="Zahl3_1" minOccurs="0"/>
			<xs:element name="OAK_BeatmungSchluessel" type="enum_0060"/>
			<xs:element name="OAK_TroponinSchluessel" type="enum_0060"/>
			<xs:element name="OAK_InotropeSchluessel" type="enum_0060"/>
			<xs:element name="OAK_Eingriffsdauer" type="Zahl3"/>
			<xs:element name="OAK_EingriffsumfangSchluessel" type="enum_0347"/>
			<xs:element name="OAK_ProzedurenAnzahl" type="Zahl1" minOccurs="0"/>
			<xs:element name="OAK_VorgehenSchluessel" type="enum_0348"/>
			<xs:choice minOccurs="0">
				<xs:element name="OAK_Bypasszeit" type="Zahl3"/>
				<xs:element name="OAK_BypasszeitUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:choice minOccurs="0">
				<xs:element name="OAK_Abklemmzeit" type="Zahl3"/>
				<xs:element name="OAK_AbklemmzeitUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:element name="OAK_AortaThorakalSchluessel" type="enum_0060"/>
			<xs:element name="OAK_NeuroprotektionSchluessel" type="enum_0060"/>
			<xs:element name="OAK_KreislaufunterstuetzungSchluessel" type="enum_0060"/>
			<xs:element name="OAK_PraeOpUnterstuetzungSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:element name="OAK_PraeOpMethodeSchluessel" type="enum_0350" minOccurs="0"/>
			<xs:element name="OAK_IntraOpUnterstuetzungSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:element name="OAK_IntraOpMethodeSchluessel" type="enum_0350" minOccurs="0"/>
			<xs:element name="OAK_AortenklappenOpAnzahl" type="Zahl2"/>
			<xs:element name="OAK_ValveInValveSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:choice minOccurs="0">
				<xs:element name="OAK_ZugangsGefaessdiameter" type="Zahl1_1"/>
				<xs:element name="OAK_ZugangsGefaessUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:element name="OAK_ZugangVerkalkungSchluessel" type="enum_0061" minOccurs="0"/>
			<xs:element name="OAK_Aortenklappenannulus" type="Zahl3" minOccurs="0"/>
			<xs:element name="OAK_MessmethodeSchluessel" type="enum_0339" minOccurs="0"/>
			<xs:choice minOccurs="0">
				<xs:element name="OAK_DistanzRca" type="Zahl3"/>
				<xs:element name="OAK_DistanzRcaUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:choice minOccurs="0">
				<xs:element name="OAK_DistanzLca" type="Zahl3"/>
				<xs:element name="OAK_DistanzLcaUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:element name="OAK_PtcaVorSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:choice minOccurs="0">
				<xs:element name="OAK_PtcaVorDurchmesser" type="Zahl2"/>
				<xs:element name="OAK_PtcaVorDurchmesserUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:element name="OAK_PtcaVorAnzahl" type="Zahl2" minOccurs="0"/>
			<xs:element name="OAK_RapidPacingVorSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:element name="OAK_RapidPacingIntraSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:element name="OAK_PtcaNachSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:choice minOccurs="0">
				<xs:element name="OAK_PtcaNachDurchmesser" type="Zahl2"/>
				<xs:element name="OAK_PtcaNachDurchmesserUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:element name="OAK_PtcaNachAnzahl" type="Zahl2" minOccurs="0"/>
			<xs:element name="OAK_RapidPacingNachSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:element name="OAK_KonversionSchluessel" type="enum_0351" minOccurs="0"/>
			<xs:element name="OAK_SuccessSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:element name="OAK_AnaesthesieSchluessel" type="enum_0352" minOccurs="0"/>
			<xs:choice minOccurs="0">
				<xs:element name="OAK_DeltaPmeanNachOp" type="Zahl3mitNull"/>
				<xs:element name="OAK_DeltaPmeanNachOpUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:element name="OAK_ResidualeInsuffizienzSchluessel" type="enum_0353" minOccurs="0"/>
			<xs:element name="OAK_ZugangVerschlussSchluessel" type="enum_0354" minOccurs="0"/>
			<xs:element name="OAK_ZusaetzlichePciSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:element name="OAK_PciWegenKhkSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:element name="OAK_PciWegenKomplikationSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:element name="OAK_LaesionenAnzahl" type="Zahl1" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>