<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="PatientenaufnahmeBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins PatientenaufnahmeBasis. 
			Es handelt sich um Daten zur Patientin bzw. zum Patienten, die bei der Aufnahme erhoben wurden.
			Elemente:
			- PAT_Alter: Alter (Berechnung muss anhand der Formel, die in der technischen Dokumentation vorgegeben ist, erfolgen)
			- PAT_Groesse: Körpergröße
			- PAT_Gewicht: Körpergewicht
			- PAT_GeschlechtSchluessel: Geschlecht
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="PatientenaufnahmeBasis">
		<xs:sequence>
			<xs:element name="PAT_Alter" type="xs:integer"/>
			<xs:element name="PAT_Groesse" type="xs:integer" minOccurs="0"/>
			<xs:element name="PAT_Gewicht" type="xs:integer" minOccurs="0"/>
			<xs:element name="PAT_GeschlechtSchluessel" type="enum_0070"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>