<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="PatientenaufnahmeKardiologie">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:include schemaLocation="./PatientenaufnahmeKardiologieBasis.xsd"/>
	<xs:include schemaLocation="./PatientenaufnahmeAortenklappe.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins PatientenaufnahmeKardiologie, welcher aus den Schemas "PatientenaufnahmeKardiologieBasis" und "PatientenaufnahmeAortenklappeBasis" besteht. 
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="PatientenaufnahmeKardiologie">
		<xs:complexContent>
			<xs:extension base="PatientenaufnahmeKardiologieBasis">
				<xs:sequence>
					<xs:element name="patientenaufnahmeAortenklappe" type="PatientenaufnahmeAortenklappe"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>


