<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="PatientenaufnahmeAortenklappeBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins PatientenaufnahmeAortenklappeBasis. 
			Es handelt sich um eine Aortenklappe-spezifische Ergänzung, in der medizinische Daten zur Patientin bzw. zum Patienten angegeben werden, die bei der Aufnahme erhoben wurden.
			Elemente:
			- PAA_DekompensationSchluessel: kardiogener Schock / Dekompensation (während der letzten 12 Monate)
			- PAA_ReanimationSchluessel: Reanimation (während der letzten 12 Monate)
			- PAA_HerzrhythmusSchluessel: Herzrhythmus
			- PAA_VorhofflimmernSchluessel: Vorhofflimmern anamnestisch bekannt
			- PAA_SchrittmacherSchluessel: Patient ist Schrittmacher- / Defi-Träger
			- PAA_BefundSchluessel: Koronare Bildgebung
			- PAA_RevaskularisationSchluessel: Myokard-Revaskularisation indiziert
			- PAA_PciSchluessel: vorausgegangene interventionelle(r) Koronareingriff(e): PCI (analog STS-Database)
			- PAA_AnzahlVorOpSchluessel: Anzahl Vor-OPs an Herz/Aorta mit Perikarderöffnung
			- PAA_AvkSchluessel: arterielle Gefäßerkrankung
			- PAA_PavkSchluessel: periphere AVK (Extremitäten)
			- PAA_ArteriaCarotisSchluessel: AVK in der Arteria Carotis
			- PAA_AortenaneurysmaSchluessel: Aortenaneurysma
			- PAA_SonstigeAvkSchluessel: sonstige arterielle Gefäßerkrankung(en)
			- PAA_LungenerkrankungSchluessel: Lungenerkrankung(en)
			- PAA_Akoef: AKÖF
			- PAA_AkoefUnbekannt: AKÖF nicht gemessen
			- PAA_AkoefMethodeSchluessel: AKÖF Messmethode
			- PAA_DeltaPmax: Delta Pmax (Echo) Aortenklappe
			- PAA_DeltaPmaxUnbekannt: Delta Pmax (Echo) Aortenklappe nicht gemessen
			- PAA_DeltaPmean: Delta Pmean (Echo) Aortenklappe
			- PAA_DeltaPmeanUnbekannt: Delta Pmean (Echo) Aortenklappe nicht gemessen
			- PAA_DeltaP: Delta P peak to peak (invasiv) Aortenklappe
			- PAA_DeltaPUnbekannt: Delta P peak to peak (invasiv) Aortenklappe nicht gemessen
			- PAA_VerkalkungsgradSchluessel: Verkalkungsgrad Aortenklappe
			- PAA_CtCalcium: CT Calcium Score
			- PAA_CtCalciumUnbekannt: CT Calcium Score nicht gemessen
			- PAA_LvotSchluessel: Verkalkung im LVOT
			- PAA_BiUnicuspideKlappeSchluessel: bicuspide/unicuspide Aortenklappe
			- PAA_AortenstenoseSchluessel: Aortenstenose (Grad)
			- PAA_AorteninsuffizienzSchluessel: Aorteninsuffizienz (Grad)
			- PAA_MitralinsuffizienzSchluessel: Mitralinsuffizienz (Grad)
			- PAA_TrikuspidalinsuffizienzSchluessel: Trikuspidalinsuffizienz (Grad)
			- PAA_ValvuloplastieSchluessel: vorausgegangene perkutane Aortenklappenvalvuloplastie
			- PAA_StsScore: STS-Score
			- PAA_HypertonusSchluessel: arterieller Hypertonus (analog STS-Database)
			- PAA_MyokardinfarktSchluessel: Myokardinfarkt (analog STS-Database)
			- PAA_SymptomeSchluessel: kardiale Symptome bei der Aufnahme (analog STS-Database)
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="PatientenaufnahmeAortenklappeBasis">
		<xs:sequence>
			<xs:element name="PAA_DekompensationSchluessel" type="enum_0361"/>
			<xs:element name="PAA_ReanimationSchluessel" type="enum_0361"/>
			<xs:element name="PAA_HerzrhythmusSchluessel" type="enum_0362"/>
			<xs:element name="PAA_VorhofflimmernSchluessel" type="enum_0363"/>
			<xs:element name="PAA_SchrittmacherSchluessel" type="enum_0364"/>
			<xs:element name="PAA_BefundSchluessel" type="enum_0357"/>
			<xs:element name="PAA_RevaskularisationSchluessel" type="enum_0365" minOccurs="0"/>
			<xs:element name="PAA_PciSchluessel" type="enum_0366"/>
			<xs:element name="PAA_AnzahlVorOpSchluessel" type="enum_0358"/>
			<xs:element name="PAA_AvkSchluessel" type="enum_0061"/>
			<xs:element name="PAA_PavkSchluessel" type="enum_0061" minOccurs="0"/>
			<xs:element name="PAA_ArteriaCarotisSchluessel" type="enum_0061" minOccurs="0"/>
			<xs:element name="PAA_AortenaneurysmaSchluessel" type="enum_0061" minOccurs="0"/>
			<xs:element name="PAA_SonstigeAvkSchluessel" type="enum_0061" minOccurs="0"/>
			<xs:element name="PAA_LungenerkrankungSchluessel" type="enum_0368"/>
			<xs:choice>
				<xs:element name="PAA_Akoef" type="Zahl1_1"/>
				<xs:element name="PAA_AkoefUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:element name="PAA_AkoefMethodeSchluessel" type="enum_0370" minOccurs="0"/>
			<xs:choice>
				<xs:element name="PAA_DeltaPmax" type="Zahl3"/>
				<xs:element name="PAA_DeltaPmaxUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:choice>
				<xs:element name="PAA_DeltaPmean" type="Zahl3"/>
				<xs:element name="PAA_DeltaPmeanUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:choice>
				<xs:element name="PAA_DeltaP" type="Zahl3"/>
				<xs:element name="PAA_DeltaPUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:element name="PAA_VerkalkungsgradSchluessel" type="enum_0371"/>
			<xs:choice minOccurs="0">
				<xs:element name="PAA_CtCalcium" type="Zahl5"/>
				<xs:element name="PAA_CtCalciumUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:element name="PAA_LvotSchluessel" type="enum_0359"/>
			<xs:element name="PAA_BiUnicuspideKlappeSchluessel" type="enum_0372"/>
			<xs:element name="PAA_AortenstenoseSchluessel" type="enum_0373"/>
			<xs:element name="PAA_AorteninsuffizienzSchluessel" type="enum_0373"/>
			<xs:element name="PAA_MitralinsuffizienzSchluessel" type="enum_0373"/>
			<xs:element name="PAA_TrikuspidalinsuffizienzSchluessel" type="enum_0360"/>
			<xs:element name="PAA_ValvuloplastieSchluessel" type="enum_0061"/>
			<xs:element name="PAA_StsScore" type="Zahl3_1" minOccurs="0"/>
			<xs:element name="PAA_HypertonusSchluessel" type="enum_0061"/>
			<xs:element name="PAA_MyokardinfarktSchluessel" type="enum_0374"/>
			<xs:element name="PAA_SymptomeSchluessel" type="enum_0375"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>