<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="PatientenaufnahmeBrustimplantatBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins PatientenaufnahmeBrustimplantatBasis. 
			Es handelt sich um eine Brustimplantat-spezifische Ergänzung, in der medizinische Daten zur Patientin bzw. zum Patienten angegeben werden, die bei der Aufnahme erhoben wurden.
			Elemente:
			- PAB_AutoimmunerkrankungSchluessel: Autoimmunerkrankung
			- PAB_VerlaufAutoimmunerkrankungSchluessel: Verlauf der Autoimmunerkrankung seit Implantation
			- PAB_GeschlechtGeburtSchluessel: Biologisches Geschlecht bei Geburt
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="PatientenaufnahmeBrustimplantatBasis">
		<xs:sequence>
			<xs:element name="PAB_AutoimmunerkrankungSchluessel" type="enum_0122"/>
			<xs:element name="PAB_VerlaufAutoimmunerkrankungSchluessel" type="enum_0123" minOccurs="0"/>
			<xs:element name="PAB_GeschlechtGeburtSchluessel" type="enum_0170" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>