<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="PatientenaufnahmeAortenklappe">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:include schemaLocation="./PatientenaufnahmeAortenklappeBasis.xsd"/>
	<xs:include schemaLocation="./InfektionAortenklappeBasis.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins PatientenaufnahmeAortenklappe, welcher aus den Schemas "PatientenaufnahmeAortenklappeBasis" und "InfektionAortenklappeBasis" besteht. 
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="PatientenaufnahmeAortenklappe">
		<xs:complexContent>
			<xs:extension base="PatientenaufnahmeAortenklappeBasis">
				<xs:sequence>
					<xs:element name="infektionAortenklappe" type="InfektionAortenklappeBasis" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>