<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="PciAortenklappeBasis">	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>	<xs:annotation>		<xs:documentation>			Dieses Schema beschreibt die Elemente des Bausteins PciAortenklappeBasis. 			Es handelt sich um die Aortenklappen-spezifischen Operationensschlüssel, die dem jeweiligen operativen Eingriff zugeordnet werden.			Elemente:			- PCA_PciArterienSchluessel: Versorgte Koronararterien		</xs:documentation>	</xs:annotation>	<xs:complexType name="PciAortenklappeBasis">		<xs:sequence>			<xs:element name="PCA_PciArterienSchluessel" type="enum_0338"/>		</xs:sequence>	</xs:complexType></xs:schema>