<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- Mit XMLSpy v2021 rel. 3 (x64) (http://www.altova.com) von  (Bundesministerium für Gesundheit) bearbeitet -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="PostoperationAortenklappeBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins PostoperationAortenklappeBasis. 
			Es handelt sich um Aortenklappen-spezifische Angaben zum postprozeduralen Verlauf.
			Elemente:
			- POA_IntraOpVerstorbenSchluessel: Patient intraprozedural verstorben
			- POA_ReanimationSchluessel: Reanimation
			- POA_SchlaganfallSchluessel: In diesem Aufenthalt neu aufgetretenes zerebrales/zerebrovaskuläres Ereignis nach VARC-3?
			- POA_NihssSchluessel: Schweregrad zerebrales/zerebrovaskuläres Ereignis nach NIHSS
			- POA_DatumSchlaganfall: Datum des (ersten) zerebralen / zerebrovaskulären Ereignisses
			- POA_MyokardinfarktSchluessel: In diesem Aufenthalt neu aufgetretener Myokardinfarkt nach VARC-3?
			- POA_DatumMyokardinfarkt: Datum des (ersten) neu aufgetretenen Myokardinfarkts
			- POA_MassnahmenSchluessel: Maßnahmen wegen Komplikationen erforderlich
			- POA_GrundMassnahmeSchluessel: Grund für Intervention
			- POA_IntensivDauer: Aufenthalt Intermediate und High Care Bereich
			- POA_AtemInsuffizienzSchluessel: respiratorische Insuffizienz
			- POA_NierenersatzSchluessel: Nierenersatztherapie neu aufgetreten innerhalb der ersten 7 Tage nach Prozedur
			- POA_MaxKreatininMikromol: höchster Kreatinin Wert i.S. in µmol/l innerhalb der ersten 7 Tage nach Prozedur
			- POA_MaxKreatininMgDl: höchster Kreatinin Wert i.S. in mg/dl innerhalb der ersten 7 Tage nach Prozedur
			- POA_MaxKreatininUnbekannt: höchster Kreatinin Wert nicht gemessen
			- POA_BlutungSchluessel: Blutungskomplikation
			- POA_ZugangKomplikationenSchluessel: Zugangsassoziierte Gefäßkomplikationen nach VARC-3
			- POA_HerzrhythmusSchluessel: Herzrhythmus bei Entlassung
			- POA_VorhofflimmernSchluessel: Im stationären Aufenthalt neu aufgetretenes Vorhofflimmern?
			- POA_AvBlockSchluessel: permanenter neuer AV-Block oder Schenkelblock
			- POA_SchrittmacherSchluessel: Patient trägt Schrittmacher / Defibrillator
			- POA_SepsisSchluessel: Sepsis (postprozedural)
			- POA_EndokarditisSchluessel: Endokarditis (postprozedural)
			- POA_DeltaPmax: Delta Pmax (Echo) Aortenklappe
			- POA_DeltaPmaxUnbekannt: Delta Pmax (Echo) Aortenklappe nicht gemessen
			- POA_DeltaPmean: Delta Pmean (Echo) Aortenklappe
			- POA_DeltaPmeanUnbekannt: Delta Pmean (Echo) Aortenklappe nicht gemessen
			- POA_Akoef: Aortenklappenöffnungsfläche AKÖF (postprozedural / bei Entlassung)
			- POA_AkoefUnbekannt: Aortenklappenöffnungsfläche AKÖF (postprozedural / bei Entlassung) nicht gemessen
			- POA_AorteninsuffizienzSchluessel: Aortenregurgitation (Aorteninsuffizienz)
			- POA_MitralinsuffizienzSchluessel: Mitralinsuffizienz (postprozedural)
			- POA_TrikuspidalinsuffizienzSchluessel: Trikuspidalinsuffizienz (postprozedural)
			- POA_Lvef: LVEF (postprozedural)
			- POA_LvefUnbekannt: LVEF (postprozedural) nicht gemessen
			- POA_VitalstatusSchluessel: Vitalstatus bei Entlassung
			- POA_TodesursacheSchluessel: Todesursache
			- POA_AggregationshemmerSchluessel: Plättchenaggregationshemmer (bei Entlassung)
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="PostoperationAortenklappeBasis">
		<xs:sequence>
			<xs:element name="POA_IntraOpVerstorbenSchluessel" type="enum_0060"/>
			<xs:element name="POA_ReanimationSchluessel" type="enum_0380"/>
			<xs:element name="POA_SchlaganfallSchluessel" type="enum_0376"/>
			<xs:element name="POA_NihssSchluessel" type="enum_0377" minOccurs="0"/>
			<xs:element name="POA_DatumSchlaganfall" type="xs:date" minOccurs="0"/>
			<xs:element name="POA_MyokardinfarktSchluessel" type="enum_0378"/>
			<xs:element name="POA_DatumMyokardinfarkt" type="xs:date" minOccurs="0"/>
			<xs:element name="POA_MassnahmenSchluessel" type="enum_0381"/>
			<xs:element name="POA_GrundMassnahmeSchluessel" type="enum_0382" minOccurs="0"/>
			<xs:element name="POA_IntensivDauer" type="Zahl3mitNull" minOccurs="0"/>
			<xs:element name="POA_AtemInsuffizienzSchluessel" type="enum_0383" minOccurs="0"/>
			<xs:element name="POA_NierenersatzSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:choice minOccurs = "0">
				<xs:element name="POA_MaxKreatininMikromol" type="Zahl4"/>
				<xs:element name="POA_MaxKreatininMgDl" type="Zahl2_1"/>
				<xs:element name="POA_MaxKreatininUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:element name="POA_BlutungSchluessel" type="enum_0384"/>
			<xs:element name="POA_ZugangKomplikationenSchluessel" type="enum_0379"/>
			<xs:element name="POA_HerzrhythmusSchluessel" type="enum_0385" minOccurs="0"/>
			<xs:element name="POA_VorhofflimmernSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:element name="POA_AvBlockSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:element name="POA_SchrittmacherSchluessel" type="enum_0364" minOccurs="0"/>
			<xs:element name="POA_SepsisSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:element name="POA_EndokarditisSchluessel" type="enum_0060" minOccurs="0"/>
			<xs:choice minOccurs="0">
				<xs:element name="POA_DeltaPmax" type="Zahl3"/>
				<xs:element name="POA_DeltaPmaxUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:choice minOccurs="0">
				<xs:element name="POA_DeltaPmean" type="Zahl3mitNull"/>
				<xs:element name="POA_DeltaPmeanUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:choice minOccurs="0">
				<xs:element name="POA_Akoef" type="Zahl1_1"/>
				<xs:element name="POA_AkoefUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:element name="POA_AorteninsuffizienzSchluessel" type="enum_0373" minOccurs="0"/>
			<xs:element name="POA_MitralinsuffizienzSchluessel" type="enum_0373" minOccurs="0"/>
			<xs:element name="POA_TrikuspidalinsuffizienzSchluessel" type="enum_0360" minOccurs="0"/>
			<xs:choice minOccurs="0">
				<xs:element name="POA_Lvef" type="Zahl3"/>
				<xs:element name="POA_LvefUnbekannt" type="JaLeer"/>
			</xs:choice>
			<xs:element name="POA_VitalstatusSchluessel" type="enum_0399"/>
			<xs:element name="POA_TodesursacheSchluessel" type="enum_0398" minOccurs="0"/>
			<xs:element name="POA_AggregationshemmerSchluessel" type="enum_0388" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>