<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="PostoperationAortenklappe">

	<xs:include schemaLocation="./PostoperationAortenklappeBasis.xsd"/>
	<xs:include schemaLocation="./AntikoagulansAortenklappeBasis.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Elemente des Bausteins PostoperationAortenklappe, welcher aus den Schemas "PostoperationAortenklappeBasis", und "AntikoagulansAortenklappeBasis" besteht. 
		</xs:documentation>
	</xs:annotation>

	<xs:complexType name="PostoperationAortenklappe">
		<xs:complexContent>
			<xs:extension base="PostoperationAortenklappeBasis">
				<xs:sequence>
					<xs:element name="antikoagulansAortenklappe" type="AntikoagulansAortenklappeBasis" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>
