<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="ProzedurenSchluesselAortenklappeBasis">	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>	<xs:annotation>		<xs:documentation>			Dieses Schema beschreibt die Elemente des Bausteins ProzedurenSchluesselAortenklappeBasis. 			Es handelt sich um die Aortenklappen-spezifischen Operationen- und Prozedurenschlüssel, die dem jeweiligen operativen Eingriff zugeordnet werden.			Elemente:			- PAK_ProzedurenSchluessel: Prozeduren (alle OPS-Kodes des durchgeführten Eingriffs)		</xs:documentation>	</xs:annotation>	<xs:complexType name="ProzedurenSchluesselAortenklappeBasis">		<xs:sequence>			<xs:element name="PAK_ProzedurenSchluessel" type="OPS"/>		</xs:sequence>	</xs:complexType></xs:schema>