<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="ProzedurenSchluesselEndoprotheseBasis">	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>	<xs:annotation>		<xs:documentation>			Dieses Schema beschreibt die Elemente des Bausteins ProzedurenSchluesselEndoprotheseBasis. 			Es handelt sich um die Endoprothesen-spezifischen Operationen- und Prozedurenschlüssel, die dem jeweiligen operativen Eingriff zugeordnet werden.			Elemente:			- PEP_ProzedurenSchluessel: OPS-Kode		</xs:documentation>	</xs:annotation>	<xs:complexType name="ProzedurenSchluesselEndoprotheseBasis">		<xs:sequence>			<xs:element name="PEP_ProzedurenSchluessel" type="OPS"/>		</xs:sequence>	</xs:complexType></xs:schema>