<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="SelbstauskunftFallBasis">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt die Teilelemente des Bausteins SelbstauskunftFallBasis. 
			Elemente:
			- FAL_Transfernummer: Transfernummer, die die Gesundheitseinrichtung von der Vertrauensstelle erhält
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="SelbstauskunftFallBasis">
		<xs:sequence>
			<xs:element name="FAL_Transfernummer" type="Transfernummer"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>