<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="TaviAortenklappeBasis">	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>	<xs:annotation>		<xs:documentation>			Dieses Schema beschreibt die Elemente des Bausteins TaviAortenklappeBasis. 			Es handelt sich um die Aortenklappe-spezifischen Operationen- und Prozedurenschlüssel, die dem jeweiligen operativen Eingriff zugeordnet werden.			Elemente:			- TAK_GrundTaviSchluessel: Grund für kathetergeführte Intervention		</xs:documentation>	</xs:annotation>	<xs:complexType name="TaviAortenklappeBasis">		<xs:sequence>			<xs:element name="TAK_GrundTaviSchluessel" type="enum_0342"/>		</xs:sequence>	</xs:complexType></xs:schema>