<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="VorbehandlungBrustimplantatBasis">	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>	<xs:annotation>		<xs:documentation>			Dieses Schema beschreibt die Elemente des Bausteins VorbehandlungBrustimplantatBasis.			Es handelt sich um Brustimplantat-spezifische Angaben zur Vorbehandlung. 			Elemente:			- VBI_BehandlungLokalSchluessel: Lokale Vorbehandlung			- VBI_BehandlungSystemischSchluessel: Systemische Vorbehandlung		</xs:documentation>	</xs:annotation>	<xs:complexType name="VorbehandlungBrustimplantatBasis">		<xs:sequence>			<xs:choice>				<xs:element name="VBI_BehandlungLokalSchluessel" type="enum_0110"/>				<xs:element name="VBI_BehandlungSystemischSchluessel" type="enum_0113"/>			</xs:choice>		</xs:sequence>	</xs:complexType></xs:schema>