<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="Warnung">
	<xs:include schemaLocation="../Datentypen/IRD_DatenTypen.xsd"/>
	<xs:include schemaLocation="./BestaetigungBasis.xsd"/>
	<xs:include schemaLocation="./HinweisBasis.xsd"/>
	
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt den Aufbau des Bausteins Warnung, welcher aus Schemas "BestaetigungBasis" und "HinweisBasis" besteht.
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="Warnung">
		<xs:sequence>
			<xs:element name="bestaetigung" type="BestaetigungBasis" minOccurs="0"/>
			<xs:element name="hinweis" type="HinweisBasis" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>