<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" id="Zubehoer">
	<xs:include schemaLocation="./ZubehoerBasis.xsd"/>
	<xs:include schemaLocation="./ZubehoerBrustimplantatBasis.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Dieses Schema beschreibt den Aufbau des Bausteins Zubehoer, welcher aus den Schemas "ZubehoerBasis", "ZubehoerBrustimplantatBasis" besteht.
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="Zubehoer">
		<xs:complexContent>
			<xs:extension base="ZubehoerBasis">
				<xs:sequence>
					<xs:element name="zubehoerBrustimplantat" type="ZubehoerBrustimplantatBasis" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>