<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <!--
=========================================================================================================
Dieses Schema ist Bestandteil der XML-Spezifikation für Datenübermittelungin der Externen Qualitätssicherung und wurde vom 
Aqua-Institut im Rahmen seiner Aufgaben als Institution nach § 137a SGB V erstellt.
Die Nutzungsbedingungen entnehmen Sie bitte dem Dokument unter:
http://www.iqtig.de/downloads/Entwicklung/Follow_up/AQUA_Nutzungsbedingungen_Programme_Dokumentationen.pdf
=========================================================================================================
-->
  <xs:include schemaLocation="../sqg_datatypes.xsd"/>
  <xs:include schemaLocation="sqg_qs_data_base.xsd"/>
  <xs:complexType name="soll_sv_type">
    <xs:complexContent>
      <xs:extension base="qs_data_type">
        <xs:sequence>
          <xs:element name="B" type="tds_modulsv_type"/>
        </xs:sequence>
        <xs:attribute name="module" type="enum_exportmodul_type" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="tds_modulsv_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="QUARTAL1">
              <xs:complexType>
                <xs:attribute name="V" use="required" type="xs:decimal"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="QUARTAL2">
              <xs:complexType>
                <xs:attribute name="V" use="required" type="xs:decimal"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="QUARTAL3">
              <xs:complexType>
                <xs:attribute name="V" use="required" type="xs:decimal"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="QUARTAL4">
              <xs:complexType>
                <xs:attribute name="V" use="required" type="xs:decimal"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="DATENSAETZE_MODUL">
              <xs:complexType>
                <xs:attribute name="V" use="required" type="xs:decimal"/>
              </xs:complexType>
            </xs:element>
	      <xs:element name="KONF_FEHLT">
              <xs:complexType>
                <xs:attribute name="V" use="optional" type="enum_jn_type"/>
              </xs:complexType>
            </xs:element>     
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>


</xs:schema>
