<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    attributeFormDefault="unqualified">
    <xs:include schemaLocation="./sqg_care_provider_base.xsd"/>
    <xs:complexType name="care_provider_type">
        <xs:annotation>
            <xs:documentation>Diese Ableitung schränkt ein auf Echtkennungen im
                Krankenhaus-Bereich</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:restriction base="care_provider_base_type">
            	<xs:sequence>
                    <xs:element ref="IKNR"/>
                	<xs:element ref="standortID" minOccurs="0"/>
                    <xs:element ref="standortIDaufn" minOccurs="0"/>
                    <xs:element ref="standortIDicd" minOccurs="0"/>
                    <xs:element ref="standortIDops" minOccurs="0"/>
                </xs:sequence>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>