<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="feedback_key_type">
		<xs:sequence>
			<xs:element name="key_name">
				<xs:annotation>
					<xs:documentation>Berichtsname</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="V" type="key_name_type" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="key_value">
				<xs:annotation>
					<xs:documentation>Das Passwort</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="V" type="key_value_type" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>
