<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    attributeFormDefault="unqualified">
    <xs:include schemaLocation="./sqg_care_provider_base.xsd"/>
    <xs:complexType name="care_provider_type">
        <xs:annotation>
            <xs:documentation>Diese Ableitung schränkt ein auf Echtkennungen im vertragsärztlichen
                Bereich</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:restriction base="care_provider_base_type">
                <xs:sequence>
                    <xs:element ref="BSNRAMBULANT">
                        <xs:annotation>
                            <xs:documentation>Betriebsstättennummer</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element ref="NBSNRAMBULANT" minOccurs="0">
                        <xs:annotation>
                            <xs:documentation>Nebenbetriebsstättennummer</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                   <!-- <xs:element ref="LANR" minOccurs="0">
                        <xs:annotation>
                            <xs:documentation>Die lebenslange Arztnummer</xs:documentation>
                        </xs:annotation>
                    </xs:element> -->
                </xs:sequence>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>