<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="sqg_software_base.xsd"/>

	<xs:complexType name="software_type">
		<xs:annotation>
			<xs:documentation xml:lang="de">Sammelelement fuer Angaben zur eingesetzten
				Software</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:restriction base="software_base_type">
				<xs:sequence>
					<xs:element name="vendor" type="organisation_without_cp_type" minOccurs="0"/>
					<xs:element name="name" type="softwareName_type" minOccurs="0"/>
					<xs:element name="version" type="softwareVersion_type" minOccurs="0"/>
					<xs:element name="release" type="softwareRelease_type" minOccurs="0"/>
					<xs:element name="specification" type="specification_type"/>
					<xs:element name="information_system" type="information_system_type"
						minOccurs="0">
						<xs:annotation>
							<xs:documentation>Sammelelelement für KIS- bzw. AIS-Produktbezeichnung
								und -Hersteller</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>

	</xs:complexType>

</xs:schema>
