<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://www.w3.org/2001/04/xmlenc#"
		schemaLocation="../imports/xenc-schema.xsd"/>
	<xs:import namespace="http://www.w3.org/2000/09/xmldsig#"
		schemaLocation="../imports/xmldsig-core-schema.xsd"/>
	<xs:include schemaLocation="sqg_encryption_base.xsd"/>
	<xs:include schemaLocation="sqg_feedback_key_cpid.xsd"/>
	<xs:complexType name="encryption_key_type">
		<xs:complexContent>
			<xs:restriction base="encryption_base_type">
				<xs:sequence>
					<xs:element ref="ds:KeyInfo" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>

</xs:schema>
