<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
	attributeFormDefault="unqualified">
	<xs:complexType name="case_base_type" >
		<xs:sequence>
			<xs:choice>
				<xs:annotation>
					<xs:documentation>Prinzipiell ist insbesondere in der Basis-Typdefintion sowohl
						das Element patient als auch das Element patient_ngkv optional. Um jedoch zu
						zeigen, dass (in Abhängikeit zum Versichertenstatus) entweder das eine oder
						das andere (Exklusiv-Oder) Element in XML übertragen werden darf, sind beide
						optionalen Elemente in eine Einfachauswahl eingebettet.</xs:documentation>
				</xs:annotation>
				<xs:element name="patient" type="patient_type" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Daten liegen je nach Position im Datenfluss entweder als
							pid/verschlüsselte pid oder als Pseudonym vor.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="patient_ngkv" type="patient_ngkv_type" minOccurs="0">
					<xs:annotation>
						<xs:documentation>zur Übertragung einer Eurotransplantnummer für die
							Verwendung im IQTIG zum Zwecke der datengestützten Qualitätssicherung.
							Daten liegen je nach Position im Datenfluss entweder als
							pid/verschlüsselte pid oder als Pseudonym vor.</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:choice>
			<xs:element name="patient_tx" type="patient_tx_type" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Zur Übertragung einer Eurotransplantnummer für die Verwendung
						im TX-Register. Daten liegen ausschließlich beim LE unverschlüsselt vor. Ab
						Übertragung an die DAS ist der Inhalt dieses Elementes im gesamten
						Datenfluss (einschließlich bis in die BAS) verschlüsselt.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="case_admin" type="case_admin_type"/>
			<xs:element name="qs_data" type="qs_data_type" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Daten liegen je nach Position im Datenfluss verschlüsselt oder
						Modulspezifisch entsprechend der Spezifikation vor</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="case_protocol_type">
		<xs:sequence>
			<xs:element name="status_case">
				<xs:complexType>
					<xs:attribute name="V" type="status_type" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="validation_item" type="validation_item_type" minOccurs="0"
				maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>
