<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:include schemaLocation="./sqg_statistic_base.xsd"/>

    <xs:complexType name="statistic_type">
    <xs:complexContent>
      <xs:restriction base="statistic_base_type">
        <xs:sequence>
          <xs:element name="sent" type="statistic_data_type" >
            <xs:annotation>
              <xs:documentation>geschickte Vorgänge</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="processed" type="statistic_data_type" >
            <xs:annotation>
              <xs:documentation>verarbeitete Vorgänge</xs:documentation>
            </xs:annotation>
          </xs:element>
          </xs:sequence>  
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>


</xs:schema>