<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">



    
    <xs:complexType  name="data_container_type">
        <xs:sequence>
            <xs:element name="care_provider" type="care_provider_type">
                <xs:annotation>
                    <xs:documentation>Angaben zum Leistungserbringer. Ist Gegenstand eines Pseudonymisierungsverfahrens der ersten Instanz nach dem Leistungserbringer und muss daher nicht gesondert verschlüsselt werden.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="cases"  type="cases_type" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>Containerelement für eine Liste von gleichartigen Vorgängen. Gleichartig bedeutet hier, Vorgänge des gleichen Moduls.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
	
</xs:schema>
