<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  attributeFormDefault="unqualified">
  <xs:include schemaLocation="sqg_patient_base.xsd"/>     <!-- für twodigitik_type, solange dieser nicht in sqg_[admin_]datatypes.xsd hinterlegt ist -->
  <xs:complexType name="patient_type">
    <xs:complexContent>
      <xs:extension base="encryption_type">
        <xs:attribute name="twodigitik" type="twodigitik_type" use="required" fixed="10"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="patient_ngkv_type">
    <xs:complexContent>
      <xs:extension base="encryption_type"/>
    </xs:complexContent>
  </xs:complexType>  
  <xs:complexType name="patient_tx_type">
    <xs:complexContent>
      <xs:extension base="encryption_type"/>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>
