<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:include schemaLocation="./sqg_cases_base.xsd"/>
  <xs:include schemaLocation="./sqg_statistic_le_qs.xsd"/>
  <xs:complexType name="cases_type">
    <xs:complexContent>
      <xs:restriction base="cases_base_type">
        <xs:sequence>
          <xs:element name="case" type="case_type" maxOccurs="unbounded"/>
          <xs:element name="statistic" type="statistic_type"/>
              </xs:sequence>  
            <xs:attributeGroup ref="cases_attributes"/>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>