<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="../sqg_admin_datatypes.xsd"/>
	<xs:include schemaLocation="sqg_body_base.xsd"/>
	<xs:complexType name="sqg_body_type">
		<xs:complexContent>
			<xs:extension base="sqg_body_base_type">
				<xs:sequence>
					<xs:element name="data_container" type="data_container_type" maxOccurs="unbounded">
						<xs:annotation>
							<xs:documentation>Ein data_container ist einem bestimmten Leistungserbringer zuzuordnenen. In der Regel sollte in einem Dokument nur ein data_container vorhanden sein. Da aber mehr als ein data_container erlaubt wird, können ggf. auch mehrere data_container für mehrere Leistungserbringer verwendet werden, wenn das Dokument zum Beispiel von einer Stelle erstellt wird, die Daten mehrerer Leistungserbringer sammelt. Dabei ist zu beachten, dass trotzdem nur Daten zu einem Modul enthalten sein dürfen.</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>
