<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:complexType name="qs_data_type">
		<xs:complexContent>
			<xs:extension base="encryption_type">
				<xs:attribute name="module" type="enum_exportmodul_type"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:annotation>
		<xs:documentation> An dieser Stelle werden alle konkreten QS-Datentypen eingefügt
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="qs_data_09n1_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_09n3_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_09n4_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_09n6_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_16n1_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_che_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_hch_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_hep_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_htxm_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_htxfu_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_kep_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_lls_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_llsfu_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_ltx_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_ltxfu_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_lutx_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_lutxfu_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_neo_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_nls_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_nlsfu_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_pci_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_pntx_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_pntxfu_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_ppci_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_mds_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_10n2_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_15n1_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_17n1_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_18n1_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_dek_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="soll_sv_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="soll_kv_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_apsy_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_papsy_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="qs_data_sep_type">
		<xs:complexContent>
			<xs:extension base="qs_data_type"/>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>