<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
xmlns:emg="http://xml.ir-d.de/emg" xmlns:stn="http://xml.ir-d.de/stn" xmlns:sak="http://xml.ir-d.de/sak" xmlns:irdma="http://xml.ir-d.de/irdma" xmlns:irdsa="http://xml.ir-d.de/irdsa" xmlns:irdsaa="http://xml.ir-d.de/irdsaa" xmlns:rst="http://xml.ir-d.de/rst" targetNamespace="http://xml.ir-d.de/rst" elementFormDefault="unqualified" version="4.1.1" id="IRD_XML_Spezifikation">
	<import namespace="http://xml.ir-d.de/emg" schemaLocation="./GEMeldung.xsd"/>
	<import namespace="http://xml.ir-d.de/stn" schemaLocation="./GEStorno.xsd"/>
	<import namespace="http://xml.ir-d.de/irdma" schemaLocation="./IRDMeldungAntwort.xsd"/>
	<import namespace="http://xml.ir-d.de/irdsa" schemaLocation="./IRDStornoAntwort.xsd"/>
	<import namespace="http://xml.ir-d.de/sak" schemaLocation="./GESelbstauskunft.xsd"/>
	<import namespace="http://xml.ir-d.de/irdsaa" schemaLocation="./IRDSelbstauskunftAntwort.xsd"/>
	
	<element name="GEMeldung" type="emg:GeMeldung">
		<annotation>
			<documentation>Meldung einer implantatbezogenen Massnahme nach § 16 IRegG. Hier: Meldung/Korrektur der Gesundheitseinrichtung an die Registerstelle. Die Meldung muss wohlgeformt und im Sinne dieses Schemas gültig sein.
			</documentation>
		</annotation>
	</element>
	<element name="GEStorno" type="stn:GeStorno">
		<annotation>
			<documentation>Stornierung einer Meldung mit allen evtl. erfolgten Korrekturen der Gesundheitseinrichtung an die Registerstelle.</documentation>
		</annotation>
	</element>
	<element name="GESelbstauskunft" type="sak:GeSelbstauskunft">
		<annotation>
			<documentation>Selbstauskunftsersuchen an die Registerstelle.</documentation>
		</annotation>
	</element>
	<element name="IRDMeldungAntwort" type="irdma:meldungAntwort">
		<annotation>
			<documentation>Antwort der Registerstelle auf eine Meldung/Korrektur der Gesundheitseinrichtung.</documentation>
		</annotation>
	</element>
	<element name="IRDStornoAntwort" type="irdsa:stornoAntwort">
		<annotation>
			<documentation>Antwort der Registerstelle auf ein Storno einer Meldung mit allen evtl. erfolgten Korrekturen der Gesundheitseinrichtung.</documentation>
		</annotation>
	</element>
	<element name="IRDSelbstauskunftAntwort" type="irdsaa:selbstauskunftAntwort">
		<annotation>
			<documentation>Antwort der Registerstelle auf ein Selbstauskunftsersuchen der Gesundheitseinrichtung.</documentation>
		</annotation>
	</element>
</schema>