<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:irdsa="http://xml.ir-d.de/irdsa" targetNamespace="http://xml.ir-d.de/irdsa" elementFormDefault="unqualified" id="StornoAntwort">

	<xs:include schemaLocation="./Bausteine/Storno.xsd"/>
	<xs:include schemaLocation="./Bausteine/EmpfangsbestaetigungBasis.xsd"/>
	<xs:include schemaLocation="./Bausteine/HinweisBasis.xsd"/>
	
	<xs:complexType name="stornoAntwort">
		<xs:sequence>
			<xs:element name="meldung" type="irdsa:Storno"/>
			<xs:element name="empfangsbestaetigung" type="irdsa:EmpfangsbestaetigungBasis"/>
			<xs:element name="fehler" type="irdsa:HinweisBasis" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>