matchbox:
  fhir:
    context:
      fhirVersion: 4.0.1
      igsPreloaded:
        - hl7.fhir.r4.core#4.0.1

spring:
  datasource:
    url: jdbc:h2:mem:matchbox
  jpa:
    properties:
      hibernate.search.enabled: false
