matchbox:
  fhir:
    context:
      fhirVersion: 4.0.1
      igsPreloaded:
        - hl7.fhir.r4.core#4.0.1

hapi:
  fhir:
    implementationguides:
      kds-senologie:
        name: kds-senologie
        version: 0.1.0
        url: file:///ig/package.tgz

spring:
  datasource:
    url: jdbc:h2:mem:matchbox
  jpa:
    properties:
      hibernate.search.enabled: false
