<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:gba:sqg" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:gba:sqg">
	
<!--
=========================================================================================================
Dieses Schema ist Bestandteil der XML-Spezifikation für Datenübermittelung in der Externen Qualitätssicherung und wurde vom
Institut für Qualitätssicherung und Transparenz im Gesundheitswesen im Rahmen seiner Aufgaben als Institution nach § 137a SGB V erstellt.
Die Nutzungsbedingungen entnehmen Sie bitte dem Dokument unter:
https://iqtig.org/impressum/
=========================================================================================================
-->
	<!-- 
========================================================================================================= 
Schema für:
Datei-Art:		QS-Daten
Schnittstelle:	Die Datenannahmestelle(KV)- nach der Entschlüsselung der QS-Daten
=========================================================================================================
-->
	<xs:include schemaLocation="../abstract/sqg_root.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_header_content_kv.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_software_le.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_document.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_encryption_feedbackkey_enc.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_body_content_le.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_cases_qs.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_case_le_fu.xsd"/>
<xs:include schemaLocation="../abstract/sqg_case_admin_default.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_patient_enc.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_care_provider_pr_cpid.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_qs_data_base.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_header_protocol.xsd"/>

	<!-- Module -->

	<xs:include schemaLocation="../interface_LE/pid/qs_data_pci_type.xsd"/>
	<xs:include schemaLocation="../interface_LE/mds/qs_data_mds_type.xsd"/>
	
	<xs:element name="root" type="sqg_root_type"/>
</xs:schema>
