<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:gba:sqg" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:gba:sqg">
	
<!--
=========================================================================================================
Dieses Schema ist Bestandteil der XML-Spezifikation für Datenübermittelung in der Externen Qualitätssicherung und wurde vom
Institut für Qualitätssicherung und Transparenz im Gesundheitswesen im Rahmen seiner Aufgaben als Institution nach § 137a SGB V erstellt.
Die Nutzungsbedingungen entnehmen Sie bitte dem Dokument unter:
https://iqtig.org/impressum/
=========================================================================================================
-->
	<!-- 
========================================================================================================= 
Schema für:
Datei-Art: 		QS-Daten (FU- und indirekte Verfahren)
Schnittstelle: 	Die Datenannahmestelle(LQS/LKG)- nach der Entschlüsselung der QS-Daten und der Pseudonymisierung der LE-Daten 
=========================================================================================================
-->
	<xs:include schemaLocation="../abstract/sqg_root.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_header_content.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_software_le.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_document_dttm.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_encryption_feedbackkey_enc.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_body_content_le.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_cases_qs.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_case_le_fu.xsd"/>
<xs:include schemaLocation="../abstract/sqg_case_admin_default.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_patient_enc.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_care_provider_kh_psn.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_qs_data_base.xsd"/>
	<xs:include schemaLocation="../abstract/sqg_header_protocol.xsd"/>

    <!-- PID-Module nach DeQS-RL -->
	<xs:include schemaLocation="../interface_LE/pid/qs_data_09n1_type.xsd"/>
	<xs:include schemaLocation="../interface_LE/pid/qs_data_09n3_type.xsd"/>
	<xs:include schemaLocation="../interface_LE/pid/qs_data_09n4_type.xsd"/>
	<xs:include schemaLocation="../interface_LE/pid/qs_data_09n6_type.xsd"/>
	<xs:include schemaLocation="../interface_LE/pid/qs_data_16n1_type.xsd"/>
	<xs:include schemaLocation="../interface_LE/pid/qs_data_hep_type.xsd"/>
	<xs:include schemaLocation="../interface_LE/pid/qs_data_17n1_type.xsd"/>
	<xs:include schemaLocation="../interface_LE/pid/qs_data_kep_type.xsd"/>
	<xs:include schemaLocation="../interface_LE/pid/qs_data_neo_type.xsd"/>
	
	<xs:include schemaLocation="../interface_LE/pid/qs_data_che_type.xsd"/>
	<xs:include schemaLocation="../interface_LE/pid/qs_data_sep_type.xsd"/>

    <xs:include schemaLocation="../interface_LE/pid/qs_data_hch_type.xsd"/>
    <xs:include schemaLocation="../interface_LE/pid/qs_data_htxm_type.xsd"/>
    <xs:include schemaLocation="../interface_LE/pid/qs_data_lls_type.xsd"/>
    <xs:include schemaLocation="../interface_LE/pid/qs_data_ltx_type.xsd"/>
    <xs:include schemaLocation="../interface_LE/pid/qs_data_lutx_type.xsd"/>
    <xs:include schemaLocation="../interface_LE/pid/qs_data_nls_type.xsd"/>

    <xs:include schemaLocation="../interface_LE/pid/qs_data_pci_type.xsd"/>
    <xs:include schemaLocation="../interface_LE/pid/qs_data_pntx_type.xsd"/>

	<xs:include schemaLocation="../interface_LE/pid/qs_data_htxfu_type.xsd"/>
	<xs:include schemaLocation="../interface_LE/pid/qs_data_llsfu_type.xsd"/>
	<xs:include schemaLocation="../interface_LE/pid/qs_data_ltxfu_type.xsd"/>
	<xs:include schemaLocation="../interface_LE/pid/qs_data_lutxfu_type.xsd"/>
	<xs:include schemaLocation="../interface_LE/pid/qs_data_nlsfu_type.xsd"/>
	<xs:include schemaLocation="../interface_LE/pid/qs_data_pntxfu_type.xsd"/>
    
    <!-- MDS - moduluebergreifend -->
    <xs:include schemaLocation="../interface_LE/mds/qs_data_mds_type.xsd"/>

	<xs:element name="root" type="sqg_root_type"/>
</xs:schema>
