<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <!--
=========================================================================================================
Dieses Schema ist Bestandteil der XML-Spezifikation für Datenübermittelung in der Externen Qualitätssicherung und wurde vom 
Institut für Qualitätssicherung und Transparenz im Gesundheitswesen im Rahmen seiner Aufgaben als Institution nach § 137a SGB V erstellt.
Die Nutzungsbedingungen entnehmen Sie bitte dem Dokument unter:
https://iqtig.org/impressum/
=========================================================================================================
-->
  <xs:include schemaLocation="../../sqg_datatypes.xsd"/>
  <xs:include schemaLocation="../../abstract/sqg_qs_data_base.xsd"/>
  <xs:complexType name="qs_data_mds_type">
    <xs:complexContent>
      <xs:extension base="qs_data_type">
        <xs:sequence>
          <xs:element name="B" type="tds_bmds_type">
            <xs:annotation>
              <xs:documentation>Bogen: Basis // Bogenzahl: 1 </xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="module" type="enum_exportmodul_type" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="tds_bmds_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:annotation>
          <xs:documentation>Exportfelder des Bogens</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="DokAbschlDat">
              <xs:annotation>
                <xs:documentation>ZusatzFeld: Dokumentationsabschlussdatum</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="datum_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ZUQSMODUL">
              <xs:annotation>
                <xs:documentation>BogenFeld: zugehöriges QS-Modul</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_modul_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="STATUSLE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Status des Leistungserbringers</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_statusle_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ARTLEMDS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Art der Leistungserbringung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_artlemds_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="DOKINSTIDENTEINGINST">
              <xs:annotation>
                <xs:documentation>BogenFeld: Verbringungsleistung (Die dokumentierende und die den Eingriff durchführende Einrichtung sind NICHT identisch)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_pciverbringungsleistung_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="kasseiknr2Stellenmds">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Ersatzfeld Institutionskennzeichen der Krankenkasse der Versichertenkarte</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="[0-9]{2}"/>
                      <xs:maxLength value="2"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="vstatusgkvmds">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: GKV-Versichertenstatus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:totalDigits value="1"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="kasseiknr2StellenmdsSp">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Ersatzfeld Institutionskennzeichen der Krankenkasse der Versichertenkarte Spender</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="[0-9]{2}"/>
                      <xs:maxLength value="2"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="vstatusgkvmdsSP">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: GKV-Versichertenstatus Spender</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:totalDigits value="1"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="BSNR">
              <xs:annotation>
                <xs:documentation>BogenFeld: Betriebsstätten-Nummer</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="[0-9]{1,2}"/>
                      <xs:maxLength value="2"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="FACHABT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Fachabteilung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="fachabt_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="alter">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Patientenalter am Aufnahmetag in Jahren</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:totalDigits value="7"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="alteramb">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Patientenalter am Behandlungstag in Jahren (ambulant)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:totalDigits value="7"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="gebjahr">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Geburtsjahr</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:gYear" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GESCHLECHTDEK">
              <xs:annotation>
                <xs:documentation>BogenFeld: Geschlecht</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_geschlechtdek_type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="aufnquartal">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Quartal des Aufnahmetages</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="quartdatum_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="OPDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Datum der Prozedur</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="datum_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="10" minOccurs="1" name="OPSCHLUESSEL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Operationen- und Prozedurenschlüssel;
alle OPS-Kodes des durchgeführten Eingriffs</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="ops301_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="EBMPCI">
              <xs:annotation>
                <xs:documentation>BogenFeld: Gebührenordnungsposition (GOP)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_ebmpci_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="1" name="EBM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Gebührenordnungsposition (GOP)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="ebm_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="30" minOccurs="1" name="ENTLDIAG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsdiagnose(n) (stationär) bzw. Quartalsdiagnose(n) (ambulant);
alle Entlassungsdiagnosen bzw. Quartalsdiagnosen, die in inhaltlichem Zusammenhang mit der in diesem Leistungsbereich dokumentierten Leistung stehen &#13;
&#13;
ICD-10-GM</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="icd10_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="entlquartal">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Quartal des Entlassungstages</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="quartdatum_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="entlwochtag">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Wochentag 1 - 7</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_wochentag_type" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="vwDauer">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Verweildauer im Krankenhaus in Tagen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" use="optional">
                  <xs:simpleType>
                    <xs:restriction base="xs:int">
                      <xs:minInclusive value="0"/>
                      <xs:totalDigits value="7"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLGRUND">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsgrund</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="enum_entlgrund_type" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
