<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <!--
=========================================================================================================
Dieses Schema ist Bestandteil der XML-Spezifikation für Datenübermittelung in der Externen Qualitätssicherung und wurde vom 
Institut für Qualitätssicherung und Transparenz im Gesundheitswesen im Rahmen seiner Aufgaben als Institution nach § 137a SGB V erstellt.
Die Nutzungsbedingungen entnehmen Sie bitte dem Dokument unter:
https://iqtig.org/impressum/
=========================================================================================================
-->
  <xs:include schemaLocation="../../sqg_datatypes.xsd"/>
  <xs:include schemaLocation="../../abstract/sqg_qs_data_base.xsd"/>
  <xs:complexType name="qs_data_hch_type">
    <xs:complexContent>
      <xs:extension base="qs_data_type">
        <xs:sequence>
          <xs:element name="B" type="gr_bhch_type">
            <xs:annotation>
              <xs:documentation>Bogen: Basis // Bogenzahl: 1 </xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
        <xs:attribute fixed="HCH" name="module" type="enum_exportmodul_type" use="required">
          <xs:annotation>
            <xs:documentation>Koronarchirurgie und Eingriffe an Herzklappen</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="tds_bhch_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:annotation>
          <xs:documentation>Exportfelder des Bogens</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="DokAbschlDat">
              <xs:annotation>
                <xs:documentation>ZusatzFeld: Dokumentationsabschlussdatum</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="kasseiknr2Stellen">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Ersatzfeld Institutionskennzeichen der Krankenkasse der Versichertenkarte</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="versichertenstatusgkv">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: GKV-Versichertenstatus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="FACHABT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Fachabteilung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="aufnquartal">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Quartal des Aufnahmetages</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="alter">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Patientenalter am Aufnahmetag in Jahren</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="gebjahr">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Geburtsjahr</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GESCHLECHT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Geschlecht</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KOERPERGROESSE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Körpergröße</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KOERPERGROESSENB">
              <xs:annotation>
                <xs:documentation>BogenFeld: Körpergröße unbekannt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KOERPERGEWICHT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Körpergewicht bei Aufnahme</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KOERPERGEWICHTNB">
              <xs:annotation>
                <xs:documentation>BogenFeld: Körpergewicht unbekannt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNNYHAERWEITERTKLAPPEN">
              <xs:annotation>
                <xs:documentation>BogenFeld: klinischer Schweregrad der Herzinsuffizienz (NYHA-Klassifikation)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ANGINAPECTORHCH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Angina Pectoris;
nach CCS</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNBEFUNDINFARKT">
              <xs:annotation>
                <xs:documentation>BogenFeld: klinisch nachgewiesene(r) Myokardinfarkt(e) STEMI oder NSTEMI</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNBEFUNDSCHOCKKARDIOGEN">
              <xs:annotation>
                <xs:documentation>BogenFeld: kardiogener Schock / Dekompensation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNBEFUNDREANIMATION">
              <xs:annotation>
                <xs:documentation>BogenFeld: Reanimation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="SYSTPULMDR">
              <xs:annotation>
                <xs:documentation>BogenFeld: systolischer Pulmonalarteriendruck</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="SYSTPULMDRNV">
              <xs:annotation>
                <xs:documentation>BogenFeld: systolischer Pulmonalarteriendruck unbekannt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNRHYTHMUS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Herzrhythmus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNBEFUNDSMTRAEGER">
              <xs:annotation>
                <xs:documentation>BogenFeld: Patient ist Schrittmacher- / Defi-Träger</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ASA">
              <xs:annotation>
                <xs:documentation>BogenFeld: Einstufung nach ASA-Klassifikation;
Es ist die ASA-Einstufung der Anästhesiedokumentation zu übernehmen.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="LVEF">
              <xs:annotation>
                <xs:documentation>BogenFeld: LVEF</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="LVEFUNBEKANNT">
              <xs:annotation>
                <xs:documentation>BogenFeld: LVEF unbekannt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KOROANGBEFUND">
              <xs:annotation>
                <xs:documentation>BogenFeld: Befund der koronaren Bildgebung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="HAUPTSTAMMSTENOSE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Hauptstammstenose</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="PCIHCH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wurde in den letzten 6 Monaten vor dem aktuellen stationären Aufenthalt ein interventioneller Koronareingriff (PCI) durchgeführt?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="PCIDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Datum letzte PCI</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="VOROPANZAHL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Anzahl</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="3" name="INFEKTIONAKUTHCH">
              <xs:annotation>
                <xs:documentation>BogenFeld: akute Infektion(en)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNBEFUNDDIABETES">
              <xs:annotation>
                <xs:documentation>BogenFeld: Diabetes mellitus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AVK">
              <xs:annotation>
                <xs:documentation>BogenFeld: arterielle Gefäßerkrankung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AVKPERIPHER">
              <xs:annotation>
                <xs:documentation>BogenFeld: periphere AVK;
Extremitäten</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AVKHIRNVERSORGEND">
              <xs:annotation>
                <xs:documentation>BogenFeld: Arteria Carotis</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AVKAORTENANEURYSMA">
              <xs:annotation>
                <xs:documentation>BogenFeld: Aortenaneurysma</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AVKSONSTIGE">
              <xs:annotation>
                <xs:documentation>BogenFeld: sonstige arterielle Gefäßerkrankung(en)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="LUNGENERKRANKUNGEN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Lungenerkrankung(en)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="NEUROLOGISCHEERKRANKUNGEN">
              <xs:annotation>
                <xs:documentation>BogenFeld: neurologische Erkrankung(en)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="RANKINSCHLAGANFALL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Schweregrad der Behinderung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="PRAENIEREERSATZTH">
              <xs:annotation>
                <xs:documentation>BogenFeld: präoperative Nierenersatztherapie</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KREATININWERTMGDL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Kreatininwert i.S. in mg/dl;
präoperativ (letzter Wert vor OP)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KREATININWERTMOLL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Kreatininwert i.S. in µmol/l;
präoperativ (letzter Wert vor OP)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="INFARKTPOSTOP">
              <xs:annotation>
                <xs:documentation>BogenFeld: neu aufgetretener Herzinfarkt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="REEING">
              <xs:annotation>
                <xs:documentation>BogenFeld: komplikationsbedingter notfallmäßiger Re-Eingriff</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENDOKARD">
              <xs:annotation>
                <xs:documentation>BogenFeld: postprozedural neu aufgetretene Endokarditis</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="PERIKARDTAMPOST">
              <xs:annotation>
                <xs:documentation>BogenFeld: Perikardtamponade</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="BLUTSCHWPOST">
              <xs:annotation>
                <xs:documentation>BogenFeld: schwerwiegende oder lebensbedrohliche Blutungen (postprozedural)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="MEDIASTINITIS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Mediastinitis;
nach den KISS-Definitionen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="CEREBROEREIGNIS">
              <xs:annotation>
                <xs:documentation>BogenFeld: zerebrales / zerebrovaskuläres Ereignis bis zur Entlassung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="abstOPzerebov">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Abstand OP-Datum - zerebrovaskuläres Ereignis</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="CEREBROEREIGNISDAUER">
              <xs:annotation>
                <xs:documentation>BogenFeld: Dauer des zerebrovaskulären Ereignisses</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="RANKINENTL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Schweregrad eines neurologischen Defizits bei Entlassung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GEFKOMPLIKAT">
              <xs:annotation>
                <xs:documentation>BogenFeld: therapiebedürftige zugangsassoziierte Komplikationen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KOMPLINFEKT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Infektion(en)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="STERNUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Sternuminstabilität</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GEFRUPTUR">
              <xs:annotation>
                <xs:documentation>BogenFeld: Gefäßruptur</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="DISSEKTION">
              <xs:annotation>
                <xs:documentation>BogenFeld: Dissektion</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="HAEMATBLUTUN">
              <xs:annotation>
                <xs:documentation>BogenFeld: therapierelevante Blutung/Hämatom</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ISCHAEMIEJL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Ischämie</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AVFISTEL">
              <xs:annotation>
                <xs:documentation>BogenFeld: AV-Fistel</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ZUGKOMPLSONST">
              <xs:annotation>
                <xs:documentation>BogenFeld: sonstige</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KOMPLMECHJN">
              <xs:annotation>
                <xs:documentation>BogenFeld: mechanische Komplikation durch eingebrachtes Fremdmaterial</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="LECKAGE">
              <xs:annotation>
                <xs:documentation>BogenFeld: paravalvuläre Leckage</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="30" name="ENTLDIAG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsdiagnose(n);
alle Entlassungsdiagnosen, die in inhaltlichem Zusammenhang mit der in diesem Verfahren dokumentierten Leistung stehen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="entlquartal">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Quartal des Entlassungstages</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="vwDauer">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Verweildauer im Krankenhaus in Tagen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLGRUND">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsgrund</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="NICHTSPEZENTLGRUND">
              <xs:annotation>
                <xs:documentation>BogenFeld: nicht spezifizierter Entlassungsgrund</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="gr_bhch_type">
    <xs:complexContent>
      <xs:extension base="tds_bhch_type">
        <xs:sequence>
          <xs:element name="bogen">
            <xs:annotation>
              <xs:documentation>Kindbögen</xs:documentation>
            </xs:annotation>
            <xs:complexType>
              <xs:sequence>
                <xs:element maxOccurs="unbounded" name="PROZ" type="gr_prozhch_type">
                  <xs:annotation>
                    <xs:documentation>Bogen: Prozedur // Existenzbedingung: keine // Bogenzahl: + </xs:documentation>
                  </xs:annotation>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="tds_prozhch_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:annotation>
          <xs:documentation>Exportfelder des Bogens</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="LFDNREINGRIFF">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wievielter Eingriff während dieses Aufenthaltes?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KONVEREINGRIFF">
              <xs:annotation>
                <xs:documentation>BogenFeld: Konversionseingriff</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="OPDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: OP-Datum</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="poopvwdauer">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Postoperative Verweildauer: Differenz in Tagen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="opquartal">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Quartal der Operation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="10" name="OPSCHLUESSEL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Operation;
alle OPS-Kodes des durchgeführten Eingriffs</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KORONARCHIRURGIE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Koronarchirurgie</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AORTENKLAPPE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Aortenklappeneingriff</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="MITREING">
              <xs:annotation>
                <xs:documentation>BogenFeld: Mitralklappeneingriff</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="WEITEINGR">
              <xs:annotation>
                <xs:documentation>BogenFeld: weitere Eingriffe am Herzen oder an herznahen Gefäßen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="TRIKUSP">
              <xs:annotation>
                <xs:documentation>BogenFeld: Eingriff an der Trikuspidalklappe</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="PULMKL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Eingriff an der Pulmonalklappe</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="VHSEPT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Eingriff am Vorhofseptum oder an der Vorhofwand</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="VHABL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Vorhofablation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="HERZNG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Eingriff an herznahen Gefäßen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="HERZOHRV">
              <xs:annotation>
                <xs:documentation>BogenFeld: Herzohrverschluss/-amputation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="INTERPCI">
              <xs:annotation>
                <xs:documentation>BogenFeld: interventioneller Koronareingriff (PCI)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="WEITEINGRSONST">
              <xs:annotation>
                <xs:documentation>BogenFeld: sonstige</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNBEFUNDBEATMUNG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Patient wird beatmet</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="DRINGLICHKEIT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Dringlichkeit</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="NITRATEIV">
              <xs:annotation>
                <xs:documentation>BogenFeld: Nitrate (präoperativ);
i. v.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="TROPONIN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Troponin positiv (präoperativ)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="INOTROPEIV">
              <xs:annotation>
                <xs:documentation>BogenFeld: Inotrope (präoperativ)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KREISLAUFUNTERSTUETZUNG">
              <xs:annotation>
                <xs:documentation>BogenFeld: (präoperativ) mechanische Kreislaufunterstützung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="PRAEOPCDC">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wundkontaminationsklassifikation;
nach Definition der CDC</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="IOPKOMPJN">
              <xs:annotation>
                <xs:documentation>BogenFeld: intraprozedurale Komplikationen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="DEVICEFEHLPOS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Device-Fehlpositionierung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GEFVERSCHLNR">
              <xs:annotation>
                <xs:documentation>BogenFeld: Koronarostienverschluss</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AORTDISSEKTION">
              <xs:annotation>
                <xs:documentation>BogenFeld: Aortendissektion</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AORTREGURGITATION">
              <xs:annotation>
                <xs:documentation>BogenFeld: Aortenregurgitation &gt; = 2. Grades</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ANNULUSRUPTUR">
              <xs:annotation>
                <xs:documentation>BogenFeld: Annulus-Ruptur</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="RUPTHERZH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Ruptur-/Perforation einer Herzhöhle</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="PERIKARDTAMPO">
              <xs:annotation>
                <xs:documentation>BogenFeld: Perikardtamponade</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="LVDEKOMPENSATION">
              <xs:annotation>
                <xs:documentation>BogenFeld: kardiale Dekompensation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="HIRNEMBOLIE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Hirnembolie</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="RHYTHMUSSTOERUNG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Rhythmusstörungen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="DEVICEEMBOLISATION">
              <xs:annotation>
                <xs:documentation>BogenFeld: Device-Embolisation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="VASKKOMPLIKAT">
              <xs:annotation>
                <xs:documentation>BogenFeld: vaskuläre Komplikation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="LOWCARD">
              <xs:annotation>
                <xs:documentation>BogenFeld: Low Cardiac Output </xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="BLUTSCHW">
              <xs:annotation>
                <xs:documentation>BogenFeld: schwerwiegende oder lebensbedrohliche Blutungen (intraoperativ/intraprozedural)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="EXITUS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Patient verstarb im OP/Katheterlabor</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="LOWCARDTH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Therapie des Low Cardiac Output</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KONVERSION">
              <xs:annotation>
                <xs:documentation>BogenFeld: Konversion</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="WECHSEING">
              <xs:annotation>
                <xs:documentation>BogenFeld: Grund für die Konversion</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="gr_prozhch_type">
    <xs:complexContent>
      <xs:extension base="tds_prozhch_type">
        <xs:sequence>
          <xs:element name="bogen">
            <xs:annotation>
              <xs:documentation>Kindbögen</xs:documentation>
            </xs:annotation>
            <xs:complexType>
              <xs:sequence>
                <xs:element minOccurs="0" name="KC" type="tds_kchch_type">
                  <xs:annotation>
                    <xs:documentation>Bogen: Koronarchirurgie // Existenzbedingung: KORONARCHIRURGIE = 1 // Bogenzahl: ? </xs:documentation>
                  </xs:annotation>
                </xs:element>
                <xs:element minOccurs="0" name="AORT" type="tds_aorthch_type">
                  <xs:annotation>
                    <xs:documentation>Bogen: Aortenklappeneingriff // Existenzbedingung: AORTENKLAPPE = 1 // Bogenzahl: ? </xs:documentation>
                  </xs:annotation>
                </xs:element>
                <xs:element minOccurs="0" name="MKE" type="tds_mkehch_type">
                  <xs:annotation>
                    <xs:documentation>Bogen: Mitralklappeneingriff // Existenzbedingung: MITREING = 1 // Bogenzahl: ? </xs:documentation>
                  </xs:annotation>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="tds_kchch_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:annotation>
          <xs:documentation>Exportfelder des Bogens</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="LFDNRKC">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wievielter koronarchirurgischer Eingriff während dieses Aufenthaltes?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ZUGANGKC">
              <xs:annotation>
                <xs:documentation>BogenFeld: Zugang (KC)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tds_aorthch_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:annotation>
          <xs:documentation>Exportfelder des Bogens</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="LFDNRAORT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wievielter Aortenklappeneingriff während dieses Aufenthaltes?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ZUGANGHCH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Zugang (AORT)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tds_mkehch_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:annotation>
          <xs:documentation>Exportfelder des Bogens</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="LFDNRMKE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wievielter Mitralklappeneingriff während dieses Aufenthaltes?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ZUGANGMKE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Zugang (MKE)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
