<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <!--
=========================================================================================================
Dieses Schema ist Bestandteil der XML-Spezifikation für Datenübermittelung in der Externen Qualitätssicherung und wurde vom 
Institut für Qualitätssicherung und Transparenz im Gesundheitswesen im Rahmen seiner Aufgaben als Institution nach § 137a SGB V erstellt.
Die Nutzungsbedingungen entnehmen Sie bitte dem Dokument unter:
https://iqtig.org/impressum/
=========================================================================================================
-->
  <xs:include schemaLocation="../../sqg_datatypes.xsd"/>
  <xs:include schemaLocation="../../abstract/sqg_qs_data_base.xsd"/>
  <xs:complexType name="qs_data_che_type">
    <xs:complexContent>
      <xs:extension base="qs_data_type">
        <xs:sequence>
          <xs:element name="B" type="gr_bche_type">
            <xs:annotation>
              <xs:documentation>Bogen: Basis // Bogenzahl: 1 </xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
        <xs:attribute fixed="CHE" name="module" type="enum_exportmodul_type" use="required">
          <xs:annotation>
            <xs:documentation>Cholezystektomie</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="tds_bche_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:annotation>
          <xs:documentation>Exportfelder des Bogens</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="DokAbschlDat">
              <xs:annotation>
                <xs:documentation>ZusatzFeld: Dokumentationsabschlussdatum</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="kasseiknr2Stellen">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Ersatzfeld Institutionskennzeichen der Krankenkasse der Versichertenkarte</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="versichertenstatusgkv">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: GKV-Versichertenstatus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="FACHABT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Fachabteilung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="gebjahr">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Geburtsjahr</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GESCHLECHT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Geschlecht</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KOERPERGROESSE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Körpergröße</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KOERPERGROESSENB">
              <xs:annotation>
                <xs:documentation>BogenFeld: Körpergröße unbekannt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KOERPERGEWICHT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Körpergewicht</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KOERPERGEWICHTNB">
              <xs:annotation>
                <xs:documentation>BogenFeld: Körpergewicht unbekannt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="aufnquartal">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Quartal des Aufnahmetages</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="alter">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Patientenalter am Aufnahmetag in Jahren</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="TRANSFUSION">
              <xs:annotation>
                <xs:documentation>BogenFeld: Transfusion/Transfusionen aufgrund eines cholezystektomiebedingten Blutverlustes?;
gemäß OPS: 8-800.-</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="100" name="ENTLDIAG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Diagnose(n);
alle Entlassungsdiagnosen, die in inhaltlichem Zusammenhang mit der in diesem Verfahren dokumentierten Leistung stehen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="STREPSEPSIS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Bestand die Streptokokkensepsis vor der Cholezystektomie?;
gemäß ICD-10-GM: A40.0, A40.1, A40.2, A40.3, A40.8, A40.9</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="SONSTSEPSIS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Bestand die sonstige Sepsis vor der Cholezystektomie?;
gemäß ICD-10-GM: A41.0, A41.1, A41.2, A41.3, A41.4, A41.51, A41.52, A41.58, A41.8, A41.9</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AKUTANAEMIE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Bestand die akute Blutungsanämie vor der Cholezystektomie?;
gemäß ICD-10-GM: D62</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AKUTPERITONITIS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Bestand die akute Peritonitis vor der Cholezystektomie?;
gemäß ICD-10-GM: K65.00, K65.09</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="SONSTPERITONITIS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Bestand die sonstige oder n.n.bez. Peritonitis vor der Cholezystektomie?;
gemäß ICD-10-GM: K65.8, K65.9</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="LEBERABSZESS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Bestand der Leberabszess vor der Cholezystektomie?;
gemäß ICD-10-GM: K75.0</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="PERFORGALLENG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Bestand die Perforation des Gallengangs vor der Cholezystektomie?;
gemäß ICD-10-GM: K83.2</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="FISTELGALLENG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Bestand die Fistel des Gallengangs vor der Cholezystektomie?;
gemäß ICD-10-GM: K83.3</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsdatum Krankenhaus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="entlquartal">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Quartal des Entlassungstages</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="vwDauer">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Verweildauer im Krankenhaus in Tagen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLGRUND">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsgrund</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="NICHTSPEZENTLGRUND">
              <xs:annotation>
                <xs:documentation>BogenFeld: nicht spezifizierter Entlassungsgrund</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="gr_bche_type">
    <xs:complexContent>
      <xs:extension base="tds_bche_type">
        <xs:sequence>
          <xs:element name="bogen">
            <xs:annotation>
              <xs:documentation>Kindbögen</xs:documentation>
            </xs:annotation>
            <xs:complexType>
              <xs:sequence>
                <xs:element maxOccurs="unbounded" name="PROZ" type="tds_prozche_type">
                  <xs:annotation>
                    <xs:documentation>Bogen: Prozedur // Existenzbedingung: keine // Bogenzahl: + </xs:documentation>
                  </xs:annotation>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="tds_prozche_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:annotation>
          <xs:documentation>Exportfelder des Bogens</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="LFDNREINGRIFF">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wievielte Prozedur?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="1" name="OPSCHLUESSEL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Prozedur während des stationären Aufenthaltes</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="OPDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Datum der Prozedur während des stationären Aufenthaltes</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
