<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <!--
=========================================================================================================
Dieses Schema ist Bestandteil der XML-Spezifikation für Datenübermittelung in der Externen Qualitätssicherung und wurde vom 
Institut für Qualitätssicherung und Transparenz im Gesundheitswesen im Rahmen seiner Aufgaben als Institution nach § 137a SGB V erstellt.
Die Nutzungsbedingungen entnehmen Sie bitte dem Dokument unter:
https://iqtig.org/impressum/
=========================================================================================================
-->
  <xs:include schemaLocation="../../sqg_datatypes.xsd"/>
  <xs:include schemaLocation="../../abstract/sqg_qs_data_base.xsd"/>
  <xs:complexType name="qs_data_neo_type">
    <xs:complexContent>
      <xs:extension base="qs_data_type">
        <xs:sequence>
          <xs:element name="B" type="tds_bneo_type">
            <xs:annotation>
              <xs:documentation>Bogen: Basis // Bogenzahl: 1 </xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
        <xs:attribute fixed="NEO" name="module" type="enum_exportmodul_type" use="required">
          <xs:annotation>
            <xs:documentation>Neonatologie</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="tds_bneo_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:annotation>
          <xs:documentation>Exportfelder des Bogens</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="DokAbschlDat">
              <xs:annotation>
                <xs:documentation>ZusatzFeld: Dokumentationsabschlussdatum</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="kasseiknr2Stellen">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Ersatzfeld Institutionskennzeichen der Krankenkasse der Versichertenkarte</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="versichertenstatusgkv">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: GKV-Versichertenstatus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="NNAMEMUTTERNV">
              <xs:annotation>
                <xs:documentation>BogenFeld: Nachname der Mutter liegt nicht vor</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="VNAMEMUTTERNV">
              <xs:annotation>
                <xs:documentation>BogenFeld: Vorname der Mutter liegt nicht vor</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="BSNR">
              <xs:annotation>
                <xs:documentation>BogenFeld: Betriebsstätten-Nummer</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="FACHABT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Fachabteilung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="VERSSTUFEAUFNKH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Versorgungsstufe des aufnehmenden Krankenhauses</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GESCHLECHT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Geschlecht</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="MEHRLINGSGEBURT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Mehrlingsgeburt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ANZMEHRLINGE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Anzahl Mehrlinge</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="LNRMEHRLING">
              <xs:annotation>
                <xs:documentation>BogenFeld: laufende Nummer des Mehrlings</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GESTALTER">
              <xs:annotation>
                <xs:documentation>BogenFeld: endgültig (postnatal) bestimmtes Gestationsalter (komplette Wochen)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GESTALTERTAGE">
              <xs:annotation>
                <xs:documentation>BogenFeld: endgültig (postnatal) bestimmtes Gestationsalter (plus zusätzliche Tage)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GEBDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Geburtsdatum des Kindes</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ltEntl">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Lebenstage des Kindes bei Entlassung aus dem Krankenhaus (in Tagen)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="alterStunden">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Alter bei Aufnahme in Stunden</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="gebjahr">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Geburtsjahr</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GEBZEIT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Uhrzeit der Geburt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GEBORTK">
              <xs:annotation>
                <xs:documentation>BogenFeld: Geburtsort des Kindes</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GEBORTKN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Geburtsort liegt nicht vor oder Geburt im Ausland</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GEBORTKBLAND">
              <xs:annotation>
                <xs:documentation>BogenFeld: Bundesland des Geburtsortes</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GEBORTKBLANDN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Das Bundesland der Geburt liegt nicht vor oder Geburt im Ausland</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Gewicht des Kindes bei Geburt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GEBORT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wo wurde das Kind geboren?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="TRANSPORTNEO">
              <xs:annotation>
                <xs:documentation>BogenFeld: Transport zur Neonatologie</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="THERAPIEVERZICHT">
              <xs:annotation>
                <xs:documentation>BogenFeld: primär palliative Therapie (ab Geburt)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KINDVERST">
              <xs:annotation>
                <xs:documentation>BogenFeld: Kind im Kreißsaal verstorben</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Aufnahmedatum (ins Krankenhaus)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ltAufn">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Lebenstage des Kindes bei Aufnahme in das Krankenhaus (in Tagen)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="monatAufn">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Monat des Aufnahmetages</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNZEIT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Uhrzeit (Aufnahme ins Krankenhaus)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNAHMEDATINPAED">
              <xs:annotation>
                <xs:documentation>BogenFeld: Aufnahmedatum in pädiatrische Abteilung;
wenn Aufnahmedatum und -uhrzeit = Geburtsdatum und -uhrzeit</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ltAufPaed">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Lebenstage des Kindes bei Aufnahme in die pädiatrische Abteilung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="abstAufnahmePaed">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Abstand zwischen Aufnahmezeitpunkt und Aufnahme in die pädiatrische Abteilung (in Minuten)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNAHMEUHRZEITPAED">
              <xs:annotation>
                <xs:documentation>BogenFeld: Uhrzeit (Aufnahme in pädiatrische Abteilung)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNAHME">
              <xs:annotation>
                <xs:documentation>BogenFeld: Aufnahme ins Krankenhaus von</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUSLIKNRKH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Aufnahme aus ausländischem Krankenhaus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNGEW">
              <xs:annotation>
                <xs:documentation>BogenFeld: Gewicht bei Aufnahme</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNKU">
              <xs:annotation>
                <xs:documentation>BogenFeld: Kopfumfang bei Aufnahme</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNKUNB">
              <xs:annotation>
                <xs:documentation>BogenFeld: Kopfumfang bei Aufnahme nicht bekannt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNTEMP">
              <xs:annotation>
                <xs:documentation>BogenFeld: Körpertemperatur bei Aufnahme</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNTEMPNB">
              <xs:annotation>
                <xs:documentation>BogenFeld: Körpertemperatur bei Aufnahme nicht bekannt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ANGEBERKRANK">
              <xs:annotation>
                <xs:documentation>BogenFeld: angeborene Erkrankungen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="5" minOccurs="1" name="ARTDERFEHLBILDUNG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Diagnose der angeborenen Erkrankung;
ICD-10-GM</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="SONO">
              <xs:annotation>
                <xs:documentation>BogenFeld: Schädelsonogramm durchgeführt/vorhanden</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="IVHAEM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Intraventrikuläre (IVH) oder periventrikuläre (PVH) Hämorrhagie</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="IVHPVHAUFNAHME">
              <xs:annotation>
                <xs:documentation>BogenFeld: Status bei Aufnahme</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="PVL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Zystische periventrikuläre Leukomalazie (PVL)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="PVLAUFNAHME">
              <xs:annotation>
                <xs:documentation>BogenFeld: Status bei Aufnahme</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUGENUNT">
              <xs:annotation>
                <xs:documentation>BogenFeld: ROP-Screening durchgeführt/vorhanden</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="DATUMUNT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Datum des ersten ROP-Screenings</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ROP">
              <xs:annotation>
                <xs:documentation>BogenFeld: Frühgeborenen-Retinopathie (ROP);
maximales Stadium während des stationären Aufenthaltes</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ROPAUFNAHME">
              <xs:annotation>
                <xs:documentation>BogenFeld: ROP-Status bei Aufnahme</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="O2GABE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Sauerstoffzufuhr jeglicher Art nach Aufnahme (von mehr als 30 Minuten)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="SAUERBEGINN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Beginn</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ltSauerBeginn">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Lebenstage des Kindes bei Beginn der Sauerstoffgabe (in Tagen)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="SAUERENDE">
              <xs:annotation>
                <xs:documentation>BogenFeld: endgültige Beendigung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ltSauerEnde">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Lebenstage des Kindes bei Ende der Sauerstoffgabe (in Tagen)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="BEATMUNG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Beatmung (von mehr als 30 Minuten) durchgeführt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="BEATBEGINN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Beginn</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ltBeatBeginn">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Lebenstage des Kindes bei Beginn der Beatmung (in Tagen)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="BEATENDE">
              <xs:annotation>
                <xs:documentation>BogenFeld: endgültige Beendigung der intratrachealen Beatmung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ltBeatEnde">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Lebenstage des Kindes bei Beendigung der Beatmung (in Tagen)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="BEATENDECPAP">
              <xs:annotation>
                <xs:documentation>BogenFeld: endgültige Beendigung jeglicher Atemhilfe</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ltBeatEndeCPAP">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Lebenstage des Kindes bei Beendigung der Beatmung incl. CPAP (in Tagen)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="PNEUMOATMUNG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Pneumothorax</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="PTORT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Ort und Zeitpunkt des Auftretens eines Pneumothorax</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="PTBEHANDL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Behandlung des Pneumothorax</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="BPD">
              <xs:annotation>
                <xs:documentation>BogenFeld: moderate oder schwere bronchopulmonale Dysplasie (BPD)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="STATUSBPD">
              <xs:annotation>
                <xs:documentation>BogenFeld: Status bei Aufnahme</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ASPHYXIE">
              <xs:annotation>
                <xs:documentation>BogenFeld: perinatale Hypoxie/Ischämie (Asphyxie)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="HIE">
              <xs:annotation>
                <xs:documentation>BogenFeld: HIE (Hypoxisch ischämische Enzephalopathie)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="SEPSIS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Sepsis</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="INFEKTIONDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Datum des Sepsis-Beginns</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="PNEUMONIENEO">
              <xs:annotation>
                <xs:documentation>BogenFeld: Pneumonie</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="abstPneuGebdat">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Abstand zwischen Geburtsdatum und Pneumonie-Beginn</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTEROKOLITIS">
              <xs:annotation>
                <xs:documentation>BogenFeld: nekrotisierende Enterokolitis (NEK) (Stadium II oder III)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="NECAUFNAHME">
              <xs:annotation>
                <xs:documentation>BogenFeld: Status bei Aufnahme</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="FIPSIP">
              <xs:annotation>
                <xs:documentation>BogenFeld: fokale intestinale Perforation (FIP) / singuläre intestinale Perforation (SIP)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="STATUSAUFNAHME">
              <xs:annotation>
                <xs:documentation>BogenFeld: Status bei Aufnahme</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="HOERSCRN">
              <xs:annotation>
                <xs:documentation>BogenFeld: Neugeborenen-Hörscreening</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="OPROP">
              <xs:annotation>
                <xs:documentation>BogenFeld: OP oder Therapie einer ROP (Frühgeborenenretinopathie)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="OPNEC">
              <xs:annotation>
                <xs:documentation>BogenFeld: OP oder sonstige invasive Therapie einer NEK (nekrotisierende Enterokolitis)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="OPFIPSIP">
              <xs:annotation>
                <xs:documentation>BogenFeld: OP oder sonstige invasive Therapie einer fokalen intestinalen Perforation (FIP) / singulären intestinalen Perforation (SIP)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="HYDROZ">
              <xs:annotation>
                <xs:documentation>BogenFeld: OP eines posthämorrhagischen Hydrozephalus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsdatum Krankenhaus/Todesdatum</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="vwDauerNeo">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Verweildauer im Krankenhaus in Tagen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="monatEntl">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Monat des Entlassungstages</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="abstAufnEntl">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Abstand zwischen Aufnahmezeitpunkt ins Krankenhaus und Entlassungs-/Todeszeitpunkt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLZEIT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsuhrzeit/Todeszeitpunkt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLGEW">
              <xs:annotation>
                <xs:documentation>BogenFeld: Körpergewicht bei Entlassung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLKU">
              <xs:annotation>
                <xs:documentation>BogenFeld: Kopfumfang bei Entlassung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLKUNB">
              <xs:annotation>
                <xs:documentation>BogenFeld: Kopfumfang bei Entlassung nicht bekannt</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="SAUERENTL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassung / Verlegung mit zusätzlichem Sauerstoffbedarf</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ERNAEHRENTL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Ernährung des Kindes bei Entlassung nach Hause / bei Verlegung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLGRUND">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsgrund</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="NICHTSPEZENTLGRUND">
              <xs:annotation>
                <xs:documentation>BogenFeld: nicht spezifizierter Entlassungsgrund</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUSLKHVERLEG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Verlegung in ein ausländisches Krankenhaus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="1" name="TODESURSACH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Todesursache</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="30" name="ENTLDIAG">
              <xs:annotation>
                <xs:documentation>BogenFeld: weitere (Entlassungs-)Diagnose(n);
alle Entlassungsdiagnosen, die in inhaltlichem Zusammenhang mit der in diesem Leistungsbereich dokumentierten Leistung stehen &#13;
&#13;
ICD-10-GM</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
