<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <!--
=========================================================================================================
Dieses Schema ist Bestandteil der XML-Spezifikation für Datenübermittelung in der Externen Qualitätssicherung und wurde vom 
Institut für Qualitätssicherung und Transparenz im Gesundheitswesen im Rahmen seiner Aufgaben als Institution nach § 137a SGB V erstellt.
Die Nutzungsbedingungen entnehmen Sie bitte dem Dokument unter:
https://iqtig.org/impressum/
=========================================================================================================
-->
  <xs:include schemaLocation="../../sqg_datatypes.xsd"/>
  <xs:include schemaLocation="../../abstract/sqg_qs_data_base.xsd"/>
  <xs:complexType name="qs_data_nls_type">
    <xs:complexContent>
      <xs:extension base="qs_data_type">
        <xs:sequence>
          <xs:element name="B" type="tds_bnls_type">
            <xs:annotation>
              <xs:documentation>Bogen: Basis // Bogenzahl: 1 </xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
        <xs:attribute fixed="NLS" name="module" type="enum_exportmodul_type" use="required">
          <xs:annotation>
            <xs:documentation>Nierenlebendspende</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="tds_bnls_type">
    <xs:sequence>
      <xs:element name="felder">
        <xs:annotation>
          <xs:documentation>Exportfelder des Bogens</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="DokAbschlDat">
              <xs:annotation>
                <xs:documentation>ZusatzFeld: Dokumentationsabschlussdatum</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="kasseiknr2StellenSp">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Ersatzfeld Institutionskennzeichen der Krankenkasse der Versichertenkarte Spender</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="versichertenstatusgkvSp">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: GKV-Versichertenstatus Spender</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="VERSICHERTENIDNEUNV">
              <xs:annotation>
                <xs:documentation>BogenFeld: Der Spender verfügt über keine eGK-Versichertennummer</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="BSNR">
              <xs:annotation>
                <xs:documentation>BogenFeld: Betriebsstätten-Nummer</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Aufnahmedatum Krankenhaus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="alter">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Patientenalter am Aufnahmetag in Jahren</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="monatAufn">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Monat des Aufnahmetages</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="FACHABT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Fachabteilung</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="EINWBAS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Liegt eine wirksame Einwilligung des Patienten zur weiteren Verarbeitung personenbezogener QS-Daten (einschließlich ET-Nummer) in der Bundesauswertungsstelle vor?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="EINWTXREG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Liegt eine wirksame Einwilligung des Patienten zur weiteren Übermittlung personenbezogener QS-Daten (einschließlich ET-Nummer) an das Transplantationsregister vor?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="EINWTXREGAUFK">
              <xs:annotation>
                <xs:documentation>BogenFeld: Wurde der Patient im Rahmen eines ärztlichen Aufklärungsgesprächs über die Einwilligung und die Folgen eines möglichen Widerrufs der Einwilligung zur Übermittlung der personenbezogenen Daten an das Transplantationsregister aufgeklärt?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="gebjahr">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Geburtsjahr</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="GESCHLECHT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Geschlecht</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KOERPERGROESSE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Körpergröße</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KGEWICHT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Körpergewicht bei Aufnahme</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="AUFNHYPERTONIE">
              <xs:annotation>
                <xs:documentation>BogenFeld: arterielle Hypertonie präoperativ;
systolisch &gt; 140 mmHg&#13;
oder&#13;
diastolisch &gt; 90 mmHg</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KREATININWERTMGDL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Kreatininwert i.S. in mg/dl;
präoperativ (letzter vorliegender Wert)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KREATININWERTMOLL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Kreatininwert i.S. in µmol/l;
präoperativ (letzter vorliegender Wert)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="OPDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: OP-Datum</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="poopvwdauer">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Postoperative Verweildauer: Differenz in Tagen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="monatOp">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Monat der Operation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="10" name="OPSCHLUESSEL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Operation;
alle OPS-Kodes des durchgeführten Eingriffs</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="OPDAUER">
              <xs:annotation>
                <xs:documentation>BogenFeld: Dauer des Eingriffs;
Schnitt-Nahtzeit</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="CLAVIENDINDO2">
              <xs:annotation>
                <xs:documentation>BogenFeld: Komplikation nach Clavien-Dindo-Klassifikation</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="BLUTUNGJL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Blutung;
&gt; 1 EK oder operative Revision</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="REOPERFORDERLICH">
              <xs:annotation>
                <xs:documentation>BogenFeld: Reoperation erforderlich</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="SONSTKOMPLIKSPEZ">
              <xs:annotation>
                <xs:documentation>BogenFeld: sonstige Komplikationen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLDIALYSE">
              <xs:annotation>
                <xs:documentation>BogenFeld: Spender bei Entlassung dialysepflichtig?</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="POSTOPKREAT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Kreatininwert i.S. in mg/dl;
bei Entlassung (letzter postoperativer Wert)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ANDPOSTOPKREAT">
              <xs:annotation>
                <xs:documentation>BogenFeld: Kreatininwert i.S. in µmol/l;
bei Entlassung (letzter postoperativer Wert)</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="QUOTALBUMINKREA">
              <xs:annotation>
                <xs:documentation>BogenFeld: Albumin-Kreatinin-Verhältnis i. U.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ALBUMINL30">
              <xs:annotation>
                <xs:documentation>BogenFeld: Albumin i. U. &gt;= 30mg/l</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ALBUMINL">
              <xs:annotation>
                <xs:documentation>BogenFeld: Albumin i. U.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLHYPERTONIE">
              <xs:annotation>
                <xs:documentation>BogenFeld: arterielle Hypertonie;
systolisch &gt; 140 mmHg&#13;
oder&#13;
diastolisch &gt; 90 mmHg</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLDATUM">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsdatum Krankenhaus</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="entlwochtag">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Wochentag 1 - 7</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="vwDauer">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Verweildauer im Krankenhaus in Tagen</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="monatEntl">
              <xs:annotation>
                <xs:documentation>ErsatzFeld: Monat des Entlassungstages</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="30" name="ENTLDIAG">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsdiagnose(n);
alle Entlassungsdiagnosen, die in inhaltlichem Zusammenhang mit der in diesem Leistungsbereich dokumentierten Leistung stehen &#13;
&#13;
ICD-10-GM</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ENTLGRUND">
              <xs:annotation>
                <xs:documentation>BogenFeld: Entlassungsgrund</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="NICHTSPEZENTLGRUND">
              <xs:annotation>
                <xs:documentation>BogenFeld: nicht spezifizierter Entlassungsgrund</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="TODESURSACHENLS">
              <xs:annotation>
                <xs:documentation>BogenFeld: Todesursache</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="V" type="xs:anySimpleType" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
